### ISSUE TITLE
How to use in docker

### ISSUE THREAD

**Issue by jimmy-walker** [yuzutech/kroki#1]
Great project.
But I am new to docker.
After launch "docker run yuzutech/kroki", how to use it to produce images?

**Comment by Mogztter** [comment]
Hello @jimmy-walker 

> After launch "docker run yuzutech/kroki", how to use it to produce images?

If you want to use it on your local machine then you will need to bind the container port 8000 to your host using the `-p` option: https://docs.docker.com/config/containers/container-networking/

So basically, if your host port 8000 is available you can bind the container port 8000 with your host port 8000:

```
docker run yuzutech/kroki -p8000:8000
```

Then go to http://localhost:8000/

I think the documentation is unclear, I will add this information in https://docs.kroki.io/kroki/setup/install/
If you have any questions, please feel free to join https://gitter.im/kroki-project/community
