### ISSUE TITLE
No Content-Type on / (info page)

### ISSUE THREAD

**Issue by MarcelWaldvogel** [yuzutech/kroki#1053]
The Kroki Docker container does not return a `Content-Type` header on requests to `/`. So, all the beautifully crafted information is not visible in browsers.

`wget -S localhost:8000` also returns:

```
--2022-01-05 13:47:14--  http://localhost:8000/
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8000... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  vary: origin
  content-length: 51198
Length: 51198 (50K)
Saving to: ‘index.html’

index.html               100%[======================================>]  50.00K  --.-KB/s    in 0s      

2022-01-05 13:47:14 (271 MB/s) - ‘index.html’ saved [51198/51198]
```

Setup: `docker-compose.yml` from the [Docker installation guide](https://docs.kroki.io/kroki/setup/use-docker-or-podman/#_run_multiple_kroki_containers_together)

Versions tested against: `latest` (=`0.16.0`), `0.15.1`, `0.14.0`.

**Comment by Mogztter** [comment]
> The Kroki Docker container does not return a Content-Type header on requests to /. 

Indeed, we should add `.putHeader(HttpHeaders.CONTENT_TYPE, "text/html");` here: https://github.com/yuzutech/kroki/blob/31f538d2b26f2742c351cf347571d95d4b25aef2/server/src/main/java/io/kroki/server/service/HelloHandler.java#L33-L35

We should also add a test to make sure that all the required headers are set. You can take inspiration from the other tests: https://github.com/yuzutech/kroki/tree/main/server/src/test/java/io/kroki/server/service

Feel free to open a pull request to fix it.

> So, all the beautifully crafted information is not visible in browsers.

I don't think that's true, at least it renders just fine using Chrome and Firefox. 

![image](https://user-images.githubusercontent.com/333276/148243606-5c028186-3106-4f47-85bc-a9b94db3231b.png)

You can give it a try: https://a.kroki.io/

**Comment by MarcelWaldvogel** [comment]
I will look into this.

> I don't think that's true, at least it renders just fine using Chrome and Firefox:

I only became aware of it, because it did *not* render fine in Firefox. But I have found the difference: My proxy adds some hardening headers by default, including `X-Content-Type-Options: nosniff`…
