### ISSUE TITLE
Add elk.jar to plantuml for using elk layout engine

### ISSUE THREAD

**Issue by MTomBosch** [yuzutech/kroki#1067]
Plantuml provides alpha support for a much improved layout engine than graphviz: Elk. 

For that to work the elk.jar must be placed next to the plantuml.jar.

It would be nice to get an updated version of kroki where this is provided for the plantuml usage.

Get more information here how to properly install the jar file: https://plantuml.com/de/elk

**Comment by Mogztter** [comment]
Thanks for creating this issue. I wasn't aware of this feature/effort.
I don't want to include alpha-version library in Kroki. As mentioned on the page:

> Do not expect too much right now, this is really an alpha-version. The idea is to get feedback from users, to know if we should continue in this direction (that is, supporting ELK within PlantUML).

When/if this feature graduates to a stable-version then we will consider integrating it.
In other words, I don't want to compromise the stability of Kroki by including a non-stable library.

If you want to use it today, it might be possible to extend the `yuzutech/kroki` image. If that's not possible, I'm inclined to make changes to make it possible to add additional/custom jar in the classpath.

**Comment by MTomBosch** [comment]
Thank you for the quick reply. I will see if I can make my own Docker image with the ELK. But your proposal (custom jars to classpath) also sounds very good.
