### ISSUE TITLE
Add support for WaveDrom

### ISSUE THREAD

**Issue by BreizhGeek** [yuzutech/kroki#107]
Hi. We would be grateful if you could add support for WaveDrom diagrams.
Original javascript version: https://wavedrom.com/tutorial.html
Python version: https://pypi.org/project/wavedrom/
Thanks!

**Comment by Mogztter** [comment]
Sounds good, I think I will go with the original version: https://github.com/wavedrom/wavedrom

**Comment by BreizhGeek** [comment]
Thanks a lot !
