### ISSUE TITLE
Feature Request: Add WireViz to providers

### ISSUE THREAD

**Issue by jjarokergc** [yuzutech/kroki#1168]
Hello, this is a feature request to add WireViz to the list of providers in kroki.  WireViz converts a yaml representation into a cable wiring diagram.

The project is located here:
https://github.com/formatc1702/WireViz

Thank you,
Jon

**Comment by Mogztter** [comment]
Hello @jjarokergc 

I believe this is a duplicate of #282 
You can add a +1 on this issue, it helps me prioritize which diagram library should be added next.
