### ISSUE TITLE
Kubernetes helm charts for Kroki

### ISSUE THREAD

**Issue by teochenglim** [yuzutech/kroki#1176]
I have developed a helm charts for kroki, it is easier to install on Kubernetes now with 2 lines of helm shell command.
Sorry i am pretty bad on asciidoc and rather not to edit it myself.

```shell
helm repo add teochenglim https://teochenglim.github.io/helm-charts/
helm upgrade --install kroki teochenglim/kroki

```

Can someone update the doc if you find it useful? thanks.
unittest is also included using "helm test kroki"

```shell

## adding helm repo
helm repo add teochenglim https://teochenglim.github.io/helm-charts/

### look for latest version of the app
helm repo update teochenglim

### installing the kroki
helm install kroki teochenglim/kroki

### install default version of the kroki helm charts
helm upgrade --install kroki teochenglim/kroki

### install default version of the kroki helm charts with your custom values
helm upgrade --install kroki teochenglim/kroki -f values.yaml

### ensure all kroki service are running (kroki, blockdiag, bpmn, Excalidraw, mermiad)
helm test kroki

### uninstall kroki
helm delete kroki

```

**Comment by Mogztter** [comment]
Don't have time right now to do it, if someone else want to step forward, please do so.
I think we should add this integration here: https://docs.kroki.io/kroki/setup/third-party-tools/

Another alternative is: https://github.com/cowboysysop/charts which also provide Helm charts for Kroki.

**Comment by TeCHiScy** [comment]
> Don't have time right now to do it, if someone else want to step forward, please do so. I think we should add this integration here: https://docs.kroki.io/kroki/setup/third-party-tools/
> 
> Another alternative is: https://github.com/cowboysysop/charts which also provide Helm charts for Kroki.

Hi @ggrossetie, would it be appropriate to mention the helm deployment method in document  https://docs.kroki.io/kroki/setup/use-kubernetes? It seems more related.

By the way,  it may be nice to put these k8s yamls directly in the repo, instead of zip them, so that yamls could be easily to update, and one can deploy the yamls using kubectl apply -f <URL> directly. Does this sound acceptable?

**Comment by ggrossetie** [comment]
> Hi @ggrossetie, would it be appropriate to mention the helm deployment method in document [docs.kroki.io/kroki/setup/use-kubernetes](https://docs.kroki.io/kroki/setup/use-kubernetes)? It seems more related.

Sounds good 👍🏻 

> By the way, it may be nice to put these k8s yamls directly in the repo, instead of zip them, so that yamls could be easily to update, and one can deploy the yamls using kubectl apply -f directly. Does this sound acceptable?

We already have files in `docs/modules/setup/examples`. Is there anything missing?

**Comment by TeCHiScy** [comment]
> We already have files in `docs/modules/setup/examples`. Is there anything missing?

Yes, it's in the `docs/modules/setup/examples/setup/attachments`, but was zipped. How about put yamls directly in the folder, instead of a zip archive? So that,
- yamls can be directly viewed/diffed/edited in Github,
- one can apply a yaml using its raw url, e.g. https://raw.githubusercontent.com/xxx, instead of downloading a zip archive & unzip it, and apply it to k8s.

**Comment by TeCHiScy** [comment]
> We already have files in `docs/modules/setup/examples`. Is there anything missing?

Oh, I see. I'll create a PR to mention the helm deployment in document.

**Comment by ggrossetie** [comment]
I found 3 Helm Charts on https://artifacthub.io/packages/search?ts_query_web=kroki&sort=relevance&page=1

- https://artifacthub.io/packages/helm/teochenglim/kroki @teochenglim 
- https://artifacthub.io/packages/helm/cowboysysop/kroki @cowboysysop (maintained by @sebastien-prudhomme) ? 
- https://artifacthub.io/packages/helm/riftbit/kroki @sebastien-prudhomme

I guess https://artifacthub.io/packages/helm/cowboysysop/kroki is the most active.

**Comment by TeCHiScy** [comment]
> I found 3 Helm Charts on https://artifacthub.io/packages/search?ts_query_web=kroki&sort=relevance&page=1
> 
> * https://artifacthub.io/packages/helm/teochenglim/kroki @teochenglim
> * https://artifacthub.io/packages/helm/cowboysysop/kroki @cowboysysop (maintained by @sebastien-prudhomme) ?
> * https://artifacthub.io/packages/helm/riftbit/kroki @sebastien-prudhomme
> 
> I guess https://artifacthub.io/packages/helm/cowboysysop/kroki is the most active.

I also think https://artifacthub.io/packages/helm/cowboysysop/kroki is the most active, and I'm currently using that.
