### ISSUE TITLE
Update to latest PlantUML v1.2022.2

### ISSUE THREAD

**Issue by wijatruangguru** [yuzutech/kroki#1182]
PlantUML v1.2022.2 has new default theme and it's nicer than current default theme. It also has json entity type. How about upgrading PlantUML in kroki to v1.2022.2?

**Comment by Mogztter** [comment]
We are using Dependabot to keep dependency up-to-date. 
The latest *stable* release is 1.2022.1: https://github.com/plantuml/plantuml/releases and we are already using it on the main branch: 

https://github.com/yuzutech/kroki/blob/eabc978298641a5044b3ec85068649c139cdbacd/server/pom.xml#L20


So we will update (automatically) to 1.2022.2 once it's available.

If you have other questions, feel free to join us in the community chat at https://kroki.zulipchat.com/.
