### ISSUE TITLE
[Question] Any idea for patch panel graph ?

### ISSUE THREAD

**Issue by gynl** [yuzutech/kroki#1242]
Hi,

I use kroki a lot and I love it! Thank you very much for this work.

I'm not sure I'm in the right place but I'm looking for a tool to make patch panel graphs. (Represent the links between the patch and the switches, etc.) Preferably in a "text" philosophy...

Anyone got anything? My searches remain fruitless... (And I don't want to switch to Visio.)

Many thanks to anyone who can help me!

**Comment by Mogztter** [comment]
Hey,

If you want to represent relations between "nodes", I guess you could try GraphViz: https://graphviz.org/Gallery/directed/
Having said that, you will probably need to the layout you want.
I also found: https://github.com/cidrblock/drawthe.net

Please ask questions on the community chat at [kroki.zulipchat.com](https://kroki.zulipchat.com/). The issue tracker is reserved for verified bug reports and feature requests. Thanks!
