### ISSUE TITLE
Is it possible to add network diagrams for Kroki?

### ISSUE THREAD

**Issue by ascheucher** [yuzutech/kroki#1248]
Network Diagrams like the one in the picture are great for documentation. Is there any chance, they could be generated with Kroki?
<img width="586" alt="Screenshot 2022-04-10 at 17 26 31" src="https://user-images.githubusercontent.com/951818/162626968-2335d02d-b204-49b2-9547-b85fa0f428e0.png">

I am sorry, but I can't suggest an existing implementation which it could be based on. Just would really appreciate to be able to use them in our WikiJS with Kroki. :)

Thanks for this great tool!

**Comment by Mogztter** [comment]
Hey, I guess you could use https://www.diagrams.net/. The latest version of Kroki includes experimental support for diagrams.net.

If you have further questions, please join the community chat at [kroki.zulipchat.com](https://kroki.zulipchat.com/) as the issue tracker is reserved for verified bug reports and feature requests. Thanks!
