### ISSUE TITLE
Diagram options for SeqDiag not respected

### ISSUE THREAD

**Issue by paescuj** [yuzutech/kroki#1251]
First of all, Kroki is awesome! Thank you!

I've noticed that the [diagram options](https://docs.kroki.io/kroki/setup/diagram-options/#_blockdiag) for sequence diagrams are not respected. I wanted to use the `no-transparency` option, but the generated image was still transparent.

Other options / diagrams might be affected as well. Unfortunately, I've no time to further debug the issue at the moment...

I've tried all the available methods to pass the option (parameter, header, payload) but none of it seems to work.

Here is an example using `curl`:
```bash
payload=$(jq  --null-input --arg source "$(cat example.seqdiag)" '{"diagram_source": $source, "diagram_type": "seqdiag", "output_format": "png", "diagram_options": {"no-transparency": true}}')
curl 'https://kroki.io' -H 'Content-Type: application/json' -d "$payload" -o 'example.png'
```

The payload looks as follows:
```json
{
  "diagram_source": "seqdiag {\n browser -> webserver [label = \"GET /seqdiag/svg/base64\"];\n webserver -> processor [label = \"Convert text to image\"];\n webserver <-- processor;\n browser <-- webserver;\n}",
  "diagram_type": "seqdiag",
  "output_format": "png",
  "diagram_options": {
    "no-transparency": true
  }
}
```

**Comment by Mogztter** [comment]
I can reproduce this issue, my guess is that the diagram options are not propagated from the gateway server to the companion server.
