### ISSUE TITLE
Bump PlantUML from 1.2022.3 to 1.2022.5 or newer 

### ISSUE THREAD

**Issue by anb0s** [yuzutech/kroki#1260]
We are using [DomainStory-PlantUML](https://github.com/johthor/DomainStory-PlantUML) and would love to use it in our local Kroki instance via stdlib include.

It was now integrated in latest [PlantUML 1.2022.5](https://github.com/johthor/DomainStory-PlantUML/issues/1#issuecomment-1120980822)

**Comment by Mogztter** [comment]
It's already on the main branch (https://github.com/yuzutech/kroki/commit/8a768ae93edaf68207cebf7f9c20260b01107f8e) and will be part of the next release 🎉

**Comment by Mogztter** [comment]
https://github.com/yuzutech/kroki/releases/tag/v0.17.1 is available (not yet deployed on https://kroki.io)
