### ISSUE TITLE
What is the best way to use kroki with GitHub pages

### ISSUE THREAD

**Issue by oakjelly21** [yuzutech/kroki#1270]
I am new to web development, and I need to parse multiple diagram libraries.
Github pages uses Jekyll, and I how do make it kroki?
Any help is appreciated.

**Comment by Mogztter** [comment]
Please join https://kroki.zulipchat.com/ to ask usage questions about Kroki. The issue tracker is reserved for reporting confirmed bugs and new feature proposals. Thanks!
