### ISSUE TITLE
Kroki 0.17.1: PlantUML and DomainStory

### ISSUE THREAD

**Issue by anb0s** [yuzutech/kroki#1272]
After update own instance to Kroki 0.17.1 i'm trying [DomainStory ](https://github.com/plantuml/plantuml-stdlib#domain-story-library) as standard include:

```
@startuml
!include <DomainStory/domainStory>
Boundary(System) {
    Person(Alice)
    Conversation(weather)
    Person(Bob)
}
activity(1, Alice, talks about the, weather, with, Bob)
@enduml
```

It works in VSCode if `http://www.plantuml.com/plantuml` is used as server:
![image](https://user-images.githubusercontent.com/95811/170246019-eaf90864-8dad-48c7-b31e-aabbcd1d717b.png)

@ official PlantUML [server](http://www.plantuml.com/plantuml/uml/JSlHgi8m3CRn-pv5pjqAWuFt8dFw0CAU85i32xODjEcaYEzk6OBcwkD7_aDMJ5g2DtyS5rySmV4g0JbEAgd-k-y-cL5AT9XgDzMi52my3RIxKSeIkxFdXUmk5ubRGrHk_Y3KbPBz_HrbjkPbS57UM6jtw67FUr3qzmmuIr7GjS4dRuDrxM4l1ugk1Fy6)

![](https://www.plantuml.com/plantuml/png/JSlHgi8m3CRn-pv5pjqAWuFt8dFw0CAU85i32xODjEcaYEzk6OBcwkD7_aDMJ5g2DtyS5rySmV4g0JbEAgd-k-y-cL5AT9XgDzMi52my3RIxKSeIkxFdXUmk5ubRGrHk_Y3KbPBz_HrbjkPbS57UM6jtw67FUr3qzmmuIr7GjS4dRuDrxM4l1ugk1Fy6)

@ our Kroki shows
![image](https://user-images.githubusercontent.com/95811/170246210-a4969ab0-69ab-4e1e-85b3-d5a41a2368eb.png)

I cannot test with official Kroki instance as it is not [yet updated](https://github.com/yuzutech/kroki/issues/1260#issuecomment-1129170320)

Any hints how to proceed?

P.S.: It looks like there is also special handling for `C4` diagrams in Kroki, do we need also something to support new PlantUML stdlibs ? How other stdlibs (Azure etc.) that are working with standard include are handled?

**Comment by anb0s** [comment]
handled in this [array](https://github.com/yuzutech/kroki/blob/9a1c5ab9231366643d5deefae3bfe6d7d1ba1af7/server/src/main/java/io/kroki/server/service/Plantuml.java#L105)

**Comment by Mogztter** [comment]
Nice catch!
Feel free to add `DomainStory` to the list and update this test: 
https://github.com/yuzutech/kroki/blob/a209cdf566ed0a02007e9436f9223eaf4bc79b57/server/src/test/java/io/kroki/server/service/PlantumlServiceTest.java#L171-L187

**Comment by anb0s** [comment]
@Mogztter thank you!

**Comment by anb0s** [comment]
@Mogztter we are waiting for DomainStory and i've to ask when the new release will be published?

**Comment by Mogztter** [comment]
Not sure, probably in the next few days depending on how much time I can allocate 😉

**Comment by Mogztter** [comment]
It's live! 🎉 

![image](https://user-images.githubusercontent.com/333276/171862514-42dfebbf-87f4-4875-b948-ef9ccc822096.png)
