### ISSUE TITLE
preserve classy stdlib includes

### ISSUE THREAD

**Issue by anb0s** [yuzutech/kroki#1274]
see in stdlib:
- [classy](https://github.com/plantuml/plantuml-stdlib#classy-library)
- [classy-c4](https://github.com/plantuml/plantuml-stdlib#classy-c4-library)

and [PlantUML integrated](https://plantuml.com/en/stdlib)

**Comment by anb0s** [comment]
will add after #1272 is accepted and working

**Comment by Mogztter** [comment]
fixed in  #1275
