### ISSUE TITLE
Set mermaid configuration

### ISSUE THREAD

**Issue by GuillaumeDesforges** [yuzutech/kroki#1326]
Mermaid has a bunch of features that need to be set at configuration level, such as [`mainBranchName` for gitGraph](https://mermaid-js.github.io/mermaid/#/gitgraph?id=gitgraph-specific-configuration-options).

Would it be possible to change mermaid configuration in a HTTP call?

**Comment by Mogztter** [comment]
Hello Guillaume,

Technically, that's possible now that we accept a [list of options](https://docs.kroki.io/kroki/setup/usage/#_options) and [propagate them to the companion containers](https://github.com/yuzutech/kroki/blob/5023863bfd81f58d46b9947e8b354d97b5352370/server/src/main/java/io/kroki/server/action/Delegator.java#L33-L37).
However, the Mermaid companion server does not retrieve the query parameters but it's possible to do so in: 

https://github.com/yuzutech/kroki/blob/5023863bfd81f58d46b9947e8b354d97b5352370/mermaid/src/index.js#L11-L36

Then, we will need to update the Mermaid default config:

https://github.com/yuzutech/kroki/blob/5023863bfd81f58d46b9947e8b354d97b5352370/mermaid/src/task.js#L5-L32

Do you want to give it a try?

**Comment by GuillaumeDesforges** [comment]
Thanks, looks feasible.

I don't have the bandwidth to do it right now, so if anyone reading this wants it they should not rely on me implementing it.

**Comment by jhogendorn** [comment]
interested in this but from a different perspective, i'd like to be able to set kroki to have a default set of options for a given engine, or perhaps even a given referrer? ie, if wiki.mydomain.com calls a kroki diagram up, it can go 'oh, yep, the theme for that is this'.

**Comment by SayakMukhopadhyay** [comment]
Hi, I am a backstage user and I have the same requirement. I will make an attempt to implement this.

**Comment by SayakMukhopadhyay** [comment]
I have created a PR which partially fulfills this issue. For now, it will pretty much work with only `theme` option for mermaid. Ngl, theme is what I personally need but I am also confused as to how to implement the other configuration params so haven't really worked on them. Let me know what you folks think.

**Comment by Mogztter** [comment]
> EDIT: Wait... do I just run main??? Seems like so...

Yes, the "gateway" server is a Vert.x stateless web app. You can indeed run the main 😉 

> I will make an attempt to implement this.

Thanks for contributing!

> I have created a PR which partially fulfills this issue. For now, it will pretty much work with only theme option for mermaid. Ngl, theme is what I personally need but I am also confused as to how to implement the other configuration params so haven't really worked on them. Let me know what you folks think.

I will have a look this week-end 👍🏻
