### ISSUE TITLE
Unable to render diagram (when too large?)

### ISSUE THREAD

**Issue by mariotoffia** [yuzutech/kroki#1332]
Hi @Mogztter  and thanks for your wonderful OSS project!! :)

I've stumbled into a problem with two of my diagrams. One is a excalidiraw and the other is diagramnet. I suspect they are too large.

Is there a way of increasing the memory?

I'm using the command:
```bash
@cat figures/overview.excalidraw | curl  -X POST --data-binary @- http://localhost:8000/excalidraw/svg > _assets/overview.svg
```
(the overview.excaldiraw is attached to this issue)
[overview.excalidraw.zip](https://github.com/yuzutech/kroki/files/9556851/overview.excalidraw.zip)

The log outputs the following:

```bash
kroki-core-1         | {"timestamp":"1663070556426","level":"INFO","thread":"vert.x-eventloop-thread-1","mdc":{"path":"/excalidraw/svg","method":"POST","service_name":"excalidraw","action":"request_received","bytes_read":"203222","user_agent":"curl/7.79.1"},"logger":"io.kroki.server.service.DiagramHandler","message":"Request received POST /excalidraw/svg","context":"default"}
kroki-core-1         | {"timestamp":"1663070556769","level":"INFO","thread":"vert.x-eventloop-thread-1","mdc":{"path":"/excalidraw/svg","took":"269","method":"POST","service_name":"excalidraw","action":"convert","file_format":"svg","user_agent":"curl/7.79.1"},"logger":"io.kroki.server.service.DiagramHandler","message":"Convert took 269ms","context":"default"}
kroki-core-1         | {"timestamp":"1663070556775","level":"ERROR","thread":"vert.x-eventloop-thread-1","mdc":{"error_message":"OK","path":"/excalidraw/svg","method":"POST","action":"error","error_code":"500","failure_class_name":"io.vertx.core.http.HttpClosedException","user_agent":"curl/7.79.1"},"logger":"io.kroki.server.error.ErrorHandler","message":"An error occurred","context":"default","exception":"io.vertx.core.http.HttpClosedException: Connection was closed\n"}
```

I'm just guessing that this line allows for diagram that are 1mb in size? (https://github.com/yuzutech/kroki/blob/5023863bfd81f58d46b9947e8b354d97b5352370/excalidraw/src/index.js#L14)

The convert function for excalidraw (index.js)
```javascript
    const diagramSource = await micro.text(req, { limit: '1mb', encoding: 'utf8' })
    if (diagramSource) {
      try {
        const svg = await worker.convert(new Task(diagramSource))
        res.setHeader('Content-Type', 'image/svg+xml')
        return micro.send(res, 200, svg)
      } catch (e) {
        console.log('e', e)
        return micro.send(res, 400, 'Unable to convert the diagram')
      }
    }
    micro.send(res, 400, 'Body must not be empty.')
  })
```

If so, is there a way of increasing the memory using e.g. some environment variable in my docker compose. I'm using yours in the _README_ file.

**Comment by eryalito** [comment]
Hey!

I found this when rendering a small but full of images excalidraw diagram. I didn't found a way of changing this limit without some code changes. Seems that the tweak on this would be minimal, maintaining backwards compatibility by just changing the line @mariotoffia says from

https://github.com/yuzutech/kroki/blob/5023863bfd81f58d46b9947e8b354d97b5352370/excalidraw/src/index.js#L14

to something like

```js
const diagramSource = await micro.text(req, { limit: (process.env.MAX_BODY_SIZE ?? '1mb'), encoding: 'utf8' })
```

I think a similar approach would be fine in other tools:
https://github.com/yuzutech/kroki/blob/main/diagrams.net/src/index.js#L22
https://github.com/yuzutech/kroki/blob/main/mermaid/src/index.js#L30
...

Would you accept a PR including these changes?
