### ISSUE TITLE
some mermaid graph can not render

### ISSUE THREAD

**Issue by zuisong** [yuzutech/kroki#1334]
this mermaid code can not render at kroki

```
gantt
    title title
    section sectionA
    A1              :crit,active,    job1, 2022-05-20,2022-05-26
    A2: milestone , m1 , after job1 , 1h

    section sectionB
    B1        :crit, active         , test, 2022-05-26,2022-06-06
    B2    : milestone      , m2, 2022-06-06,1h

    section sectionC
    C1                      :crit, prod,after test,24h


```

![image](https://user-images.githubusercontent.com/19145952/190337120-2f4b5cbe-6ea3-4f29-922e-6224ace1e0d0.png)

![image](https://user-images.githubusercontent.com/19145952/190337540-2a4459cd-ef44-455d-9c0b-06aa2c6cea0d.png)

**Comment by Mogztter** [comment]
Hey 👋
I don't think it's related to this particular diagram but we are experiencing instabilities on the Mermaid container: https://github.com/yuzutech/kroki/issues/1319

I haven't yet been able to figure out what's going on.
Since this issue is a duplicate, I will close it.
