### ISSUE TITLE
Update UMLet to newest Version (including documentation)

### ISSUE THREAD

**Issue by castler** [yuzutech/kroki#1353]
There is a new version of UMLet out in the wide (Version: 15.0.0).
If diagrams are created via this version and rendered with Kroki, the diagrams look different as when created with the 14.3.0 version of UMLet. 

This is most certainly caused by the major version update - and thus breaking changes.

We would like to update the UMLet Version in Kroki to 15.0.0.
One thing we noticed is that Kroki uses `umlet-mini.jar`, but we could not find build instructions.

It would be awesome if we could:

- [ ] Provide instructions for umlet-min build to enable open source contributions in that area
- [ ] Update UMLet Version within Kroki to 15.0.0

**Comment by Mogztter** [comment]
UMlet mini is built from this fork https://github.com/yuzutech/umlet/tree/mini (branch `mini`).
I guess you will need to sync the fork with upstream.
You can use Maven to produce a jar.

Once you've replaced the UMlet jar in Kroki, you will need to update the pom.xml and the `installLocalDependencies` task :

https://github.com/yuzutech/kroki/blob/d625735ff265c2032c7053b39353005ffe672129/Makefile#L11

**Comment by Mogztter** [comment]
@castler Let me know if you need any additional information. Once you've successfully updated UMLet, I think we should add a README in https://github.com/yuzutech/kroki/tree/main/umlet to explain (in length) how to do it.

**Comment by castler** [comment]
Hi @Mogztter all great thanks!

I have it on my todo list and will definetly have a look (even if it will take some more time)

**Comment by ggrossetie** [comment]
main branch is now using UMLet 15.0.0
