### ISSUE TITLE
Break statement fails with mermaid

### ISSUE THREAD

**Issue by Jahmilli** [yuzutech/kroki#1366]
Hey, i've noticed that when using the 'break' statement with mermaid for sequence diagrams, it results in a `400 OK` and does not render the diagram. Please see the image below of an example test on https://kroki.io/
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/19684692/200226977-4c8ff2ea-0c05-4590-98fc-cf72c345b77e.png">

Note that the same UML works on https://mermaid.live/
<img width="1698" alt="image" src="https://user-images.githubusercontent.com/19684692/200227118-3ca70b48-d0b7-47bc-b325-fe96b876051c.png">

The example is 

```
sequenceDiagram
    Consumer-->API: Book something
    API-->BookingService: Start booking process
    break when the booking process fails
        API-->Consumer: show failure
    end
    API-->BillingService: Start billing process
```

Note that with kroki, i get the same error result when running Kroki locally with a docker container, where the container logs 

```json

{
  "timestamp": "1667794155439",
  "level": "ERROR",
  "thread": "vert.x-eventloop-thread-1",
  "mdc": {
    "error_message": "Syntax error in graph",
    "path": "mermaid:8002/mermaid/svg",
    "method": "POST",
    "action": "delegate",
    "error_code": "400"
  },
  "logger": "io.kroki.server.action.Delegator",
  "message": "Unsuccessful request POST mermaid:8002/mermaid/svg - response: {statusCode:400 body: Syntax error in graph}",
  "context": "default"
}
```

Please let me know if you need any additional information. Happy to help contribute if possible! :)

**Comment by Mogztter** [comment]
It might be because we are not using the latest version. Do you know if `break` is a new feature?

**Comment by Jahmilli** [comment]
Hey, yeh I can see that it was added into their [9.1.2 release](https://github.com/mermaid-js/mermaid/releases/tag/9.1.2) on June 15 as part of this PR https://github.com/mermaid-js/mermaid/pull/3063

Given that the last release for this for this was June 2, then yeh a version update or whatever is required sounds necessary.

**Comment by Mogztter** [comment]
The current latest version of Kroki (0.17.1) is using Mermaid 9.1.1.
Main branch is already using Mermaid 9.2.0 and a new release of Kroki is coming now.

**Comment by Jahmilli** [comment]
closing this as it's been fixed in the newest version, thanks for it! 🚀
