### ISSUE TITLE
Issue loading external sprites

### ISSUE THREAD

**Issue by fredrike** [yuzutech/kroki#1372]
This simple [Hello World](https://github.com/plantuml-stdlib/Azure-PlantUML#hello-world) using external sprites:

```
@startuml Hello World
!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/release/2-1/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Databases/all.puml
!includeurl AzurePuml/Compute/AzureFunction.puml

actor "Person" as personAlias
AzureFunction(functionAlias, "Label", "Technology", "Optional Description")
AzureCosmosDb(cosmosDbAlias, "Label", "Technology", "Optional Description")

personAlias --> functionAlias
functionAlias --> cosmosDbAlias

@enduml
```

Ends up with Error 400: Syntax Error

![Diagram](https://kroki.io/plantuml/svg/eNqdTz1PxDAM3fMrcp0OiTaCkQHdiQoxHKIDiNlNfddIbhLFjhD8etpeEXSAge09vw_bOxZIkgfSD0gU9GtI1KlNh0fnUe8_csJmUnuRyDfGJHirTk763GbGZIMX9FLZMJhI4KeikqUj15o5WzbT9OXxYBISAqO5Lq9M51jUxnlLucOc6HvPOXUXhiH4Ko6DX2w1CLRjHRsg-ss4VsUseO69z96K-2pWYCUkXTSYOPhCA-s4wz05YLVKbI8LmLVLXRygRSpG8Iy294HC6X1iT3EyAeka2SY3s-JCLV_xELhut3YB_-tSP47UZXmrV6epFZv11Tqldui78f1PXaK1eg==)

[Edit this diagram](https://niolesk.top/#https://kroki.io/plantuml/svg/eNqdTz1PxDAM3fMrcp0OiTaCkQHdiQoxHKIDiNlNfddIbhLFjhD8etpeEXSAge09vw_bOxZIkgfSD0gU9GtI1KlNh0fnUe8_csJmUnuRyDfGJHirTk763GbGZIMX9FLZMJhI4KeikqUj15o5WzbT9OXxYBISAqO5Lq9M51jUxnlLucOc6HvPOXUXhiH4Ko6DX2w1CLRjHRsg-ss4VsUseO69z96K-2pWYCUkXTSYOPhCA-s4wz05YLVKbI8LmLVLXRygRSpG8Iy294HC6X1iT3EyAeka2SY3s-JCLV_xELhut3YB_-tSP47UZXmrV6epFZv11Tqldui78f1PXaK1eg==)

While it works fine on [plantuml.com](https://www.plantuml.com/plantuml/uml/dKyxJmCn3DxpAzARYiGrWf41jQ9234Lq037x4hUDv3mKEqBmwxb74Tm00zlt-NlONhD0aHf8Fo1Hqg-fa5CBXmSVKMy-Qi7ze9v4CjyOK-1jTVHogbrbB3P5mIWhcuB9174eQbaS-SwCsNO_J5yUTwOW8J2Qw_RAEC-Y5ZvQgWvheUyzK-ekXP3YAlU3NsnR4EY0aGqG_MNigt8Ld7hlQxJYlveLM4b5Dtiid6AZWNKUuOOyi9ebbeS9JDgbRdRG8JKzU4PxYedIyNrWJtam0UajiYr-PCs5Ed_58V6sMzep-5-N-d6aRjjRFJjDpTYepzOfjSReQg1F)

![fig](https://www.plantuml.com/plantuml/png/dKyxJmCn3DxpAzARYiGrWf41jQ9234Lq037x4hUDv3mKEqBmwxb74Tm00zlt-NlONhD0aHf8Fo1Hqg-fa5CBXmSVKMy-Qi7ze9v4CjyOK-1jTVHogbrbB3P5mIWhcuB9174eQbaS-SwCsNO_J5yUTwOW8J2Qw_RAEC-Y5ZvQgWvheUyzK-ekXP3YAlU3NsnR4EY0aGqG_MNigt8Ld7hlQxJYlveLM4b5Dtiid6AZWNKUuOOyi9ebbeS9JDgbRdRG8JKzU4PxYedIyNrWJtam0UajiYr-PCs5Ed_58V6sMzep-5-N-d6aRjjRFJjDpTYepzOfjSReQg1F)

**Comment by Mogztter** [comment]
You should use the standard library:

```puml
@startuml Hello World
!include <Azure/AzureCommon>
!include <Azure/Databases/all>
!include <Azure/Compute/AzureFunction>

actor "Person" as personAlias
AzureFunction(functionAlias, "Label", "Technology", "Optional Description")
AzureCosmosDb(cosmosDbAlias, "Label", "Technology", "Optional Description")

personAlias --> functionAlias
functionAlias --> cosmosDbAlias
@enduml
```

https://plantuml.com/en/stdlib

For security reasons, https://kroki.io does not load content from remote URLs. You can of course allow it when running Kroki locally.

**Comment by fredrike** [comment]
Thanks a lot!

Perhaps this should be mentioned somewhere on the frontpage..

**Comment by fredrike** [comment]
I mean on https://kroki.io/, at least mention that external includes not are allowed.
