### ISSUE TITLE
How to add CJK fonts on kroki-diagramsnet?

### ISSUE THREAD

**Issue by ajeep8** [yuzutech/kroki#1384]
I copy some Chinese font files in /usr/share/fonts of kroki-diagramsnet docker container, but the output png is still blank rectangle on Chinese word.

**Comment by Mogztter** [comment]
You might need to update the font cache using `RUN fc-cache -f`.
Please ask your question in the project chat at https://kroki.zulipchat.com/ and someone will likely be able to help you.
