### ISSUE TITLE
unexpected keyword argument 'attachment_filename'

### ISSUE THREAD

**Issue by solariz** [yuzutech/kroki#1392]
Hey,

when Creating PNG from e.g. RackDiag sources I receive the Error:

`400 send_file() got an unexpected keyword argument 'attachment_filename'`

Found a similar Issue [somewhere Else](https://github.com/pallets/flask/issues/4753) with the explanation that **attachment_filename** was changed into **download_name**:

**Comment by Mogztter** [comment]
Indeed, we are still using `attachment_filename`:

https://github.com/yuzutech/kroki/blob/b9f136c2389fb4abfc22648f14ed7acff5313f79/blockdiag/src/server.py#L70

Never noticed the warning/deprecation message, I need to configure the logger on the blockdiag container and we should add a test in:

https://github.com/yuzutech/kroki/blob/b9f136c2389fb4abfc22648f14ed7acff5313f79/ci/tests/smoke.js#L10


Would you like to submit a pull request?

**Comment by zeldigas** [comment]
@Mogztter https://kroki.io still has this issue. Any plans to update it?
