### ISSUE TITLE
Publish an ARM64 image on Docker Hub

### ISSUE THREAD

**Issue by dan-burt** [yuzutech/kroki#1401]
I believe the build scripts have ARM64 compatibility within them. When I try to recompile this, I am missing a bunch of dependencies so it errors. I don't necessarily want to deploy them just for this single image, and given that it is seemingly in the config, I was wondering why a published ARM64 image is not made up on Docker Hub?

**Comment by Mogztter** [comment]
They should be available on Docker Hub which one is missing?

Could you please the command you are using?

**Comment by dan-burt** [comment]
If I search on Docker Hub for "kroki" and then filter for the ARM64 architecture, the companion images are still listed, but not the main image.

There is another, `kjelljoakim/kroki` image but there are no details or tags provided.

I don't have, nor need, Maven installed, which is the latest error message I am receiving.

**Comment by Mogztter** [comment]
As far as I know the main container is compatible with arm64 we don't need a special image for arm64.

**Comment by mh35** [comment]
I checked the image, and no arm64 image found in yuzutech/kroki.
I read the code, and I found kroki image depends on eclipse-temurin image, and it is not compatible with arm64 architecture.
See [kroki/server/ops/docker/jdk11-alpine/Dockerfile](https://github.com/yuzutech/kroki/blob/main/server/ops/docker/jdk11-alpine/Dockerfile).

**Comment by Mogztter** [comment]
`eclipse-temurin` does provide arm64 images but not for Alpine. I'm leaning toward using Ubuntu base image (instead of Alpine) because it has better support across tools/languages/compilers.

As you can see, `eclipse-temurin:11.0.17_8-jre-jammy` is available on `linux/amd64` and `linux/arm64/v8`: https://hub.docker.com/layers/library/eclipse-temurin/11.0.17_8-jre-jammy/images/sha256-772b0000ef09d2099ef07d1df87b12d942248419e79ff46fa739a5feb617e543?context=explore

**Comment by FelixVanOost** [comment]
@Mogztter do you need any support making or testing this change? I'm looking to deploy Kroki on some `arm64` machines pretty soon so I can provide feedback if needed.

**Comment by FelixVanOost** [comment]
I also noticed that the companion containers don't have an `arm64` image available under the `latest` tag, even though one exists for specific version tags. For example, `kroki-mermaid:0.18.0` has both `amd64` and `arm64` images available, but `kroki-mermaid:latest` only has an `amd64` image available.

**Comment by Mogztter** [comment]
Interesting, it might be an improper use of `docker bake` or a bug:

https://github.com/yuzutech/kroki/blob/7a5b57c7d9bbbeab7715b044d599325302971920/Makefile#L33

I would expect the above configuration to publish on both the `latest` and version tags.

**Comment by FelixVanOost** [comment]
Looks like publishing to `latest` is resolved as of a few days ago; I can now see both `linux/arm64` and `linux/amd64` images for the companion containers on Docker Hub. 🥳

I can work on getting an Ubuntu base image working with the Kroki image and submitting a PR if that would help!

**Comment by ggrossetie** [comment]
Great news!

> I can work on getting an Ubuntu base image working with the Kroki image and submitting a PR if that would help!

Could you please try to run the current image `yuzutech/kroki` on arm64? Last time I tried it was working (even though only `linux/amd64` was available).

We can create an issue/proposal to move from Alpine to Ubuntu but I don't want to rush. We should discuss each advantage and disadvantage before making the move.

**Comment by FelixVanOost** [comment]
I get the following error when attempting to run a Kroki container (0.19.0) on a `linux/arm64` machine:

```
exec /bin/sh: exec format error
```

Which is expected when an image doesn't the platform it's trying to run on.
