### ISSUE TITLE
Mermaid classDiagram "note" and "note for class" not working

### ISSUE THREAD

**Issue by codingluke** [yuzutech/kroki#1421]
```mermaid
classDiagram
    class Foo
    note for Foo "hello"
```

![CleanShot 2023-01-06 at 15 33 33@2x](https://user-images.githubusercontent.com/643436/211032876-47177fed-3149-4056-a5cb-e98bbec351b0.png)

**Comment by Mogztter** [comment]
It does not work on GitHub either:

<img width="822" alt="Capture d’écran 2023-01-06 à 18 33 36" src="https://user-images.githubusercontent.com/333276/211076274-675d6ba5-bbe4-474a-a2ea-46dd98050c41.png">

This feature is available in Mermaid 9.3 and the latest release of Kroki is using 9.2 so it will be "resolved" when a new version of Kroki is released.
