### ISSUE TITLE
Update docs for Java 11

### ISSUE THREAD

**Issue by 0xflotus** [yuzutech/kroki#1427]
From the [Changelog of the v0.18.0](https://github.com/yuzutech/kroki/releases/tag/v0.18.0) Release:

> The minimum Java version to run the gateway server is now Java 11.

From the [official Kroki documentation](https://docs.kroki.io/kroki/setup/manual-install/):

> You’ve installed Java 8 on your Linux machine.

Should this be updated, so you need minimum Java 11 to start the Kroki server?

**Comment by Mogztter** [comment]
Good catch! yes we need to update it 👍🏻

**Comment by ggrossetie** [comment]
Updated: https://github.com/yuzutech/kroki/commit/a127cc2b29567db61713db8ecddc587a02b2a2b8
