### ISSUE TITLE
`Diagram it` is down

### ISSUE THREAD

**Issue by 0xflotus** [yuzutech/kroki#1429]
In the [Third Party Tools section of the docs](https://docs.kroki.io/kroki/setup/third-party-tools/) you refer to a public service named [`Diagram it`](https://diagramit.herokuapp.com/). It seems this service is down. 

Maybe this is caused by Herokus Shutdown of the free tier?
If the service don't get up again, maybe consider to remove Diagram it from the docs?

**Comment by Mogztter** [comment]
@marvst are you still working/maintaining https://diagramit.herokuapp.com/? Otherwise, we will remove it from the docs.

**Comment by ggrossetie** [comment]
diagramit was removed from the documentation: https://github.com/yuzutech/kroki/commit/a127cc2b29567db61713db8ecddc587a02b2a2b8
