### ISSUE TITLE
CORS access blocked because of header

### ISSUE THREAD

**Issue by RK-RS** [yuzutech/kroki#1449]
Hi when trying to get an image (svg or png) from a self hosted kroki instance for a confluence instance sometimes this error appears: 

`Access to XMLHttpRequest at '${KROKI-DIAGRAM-LINK}' from origin '${CONFLUENCE-LINK}' has been blocked by CORS policy: Request header field x-atlassian-mau-ignore is not allowed by Access-Control-Allow-Headers in preflight response.`

is there a way to manually allow this header for CORS through for example setting an env variable in the Docker file?

Running the latest kroki version btw.

**Comment by ggrossetie** [comment]
Indeed, we do not allow the `x-atlassian-mau-ignore` header:

https://github.com/yuzutech/kroki/blob/39017985ebcd0ce9e72ff34140bdc79816fd270b/server/src/main/java/io/kroki/server/Server.java#L93-L97

Currently, this setting is static but I would gladly merge a pull request to make it configurable.

**Comment by RK-RS** [comment]
Added pull request: https://github.com/yuzutech/kroki/pull/1468
