### ISSUE TITLE
[Information Request] Release Cycle

### ISSUE THREAD

**Issue by copyrights** [yuzutech/kroki#1451]
Would you mind describing your release strategy?
What are the preconditions? Are there certain events?
Is there a timeline?

**Comment by ggrossetie** [comment]
To be honest I don't really have a release strategy. I'm trying to release every 2 months or so. The precondition is me having free time 😉 

https://kroki.io had a few instabilities the past month and I need to investigate. Usually, it's either an issue with Puppeteer/Chrome or an infinite loop/very long processing in the Java process (PlantUML, UMlet...).

I also spend a few hours (depending on the release size) to create release notes. I guess we could mandate that every pull request must update a CHANGELOG file.

Are you waiting on something specific?

**Comment by copyrights** [comment]
Thanks for your answer and that you spend your free time for this project, much appreciated.

Yes, I would like to see the wireviz #1439 implementation in the wild.

**Comment by copyrights** [comment]
Maybe this could help you for the next release

# Changelog

## Bug Fixes

This release includes a new diagram library: [WireViz](https://github.com/formatc1702/WireViz)

It also contains the latest available versions of:

- DBML
  

In addition, it includes a few improvements and bug fixes.

## Improvements

- Integrate [WireViz](https://github.com/formatc1702/WireViz) by @copyrights :tada:
  
- Bump DBML-Renderer from 1.0.22 to 1.0.26 by @bobzomer
  

## Infrastructure

## Documentation

- fix docker image name by @rfdonnelly in #1438
  
- fix GitLab capitalization by @fdmarcin in #1454
  

# New Contributors

- @copyright made their first contribution in #1439
  
- @fdmarcin made their first contributionin #1454
  
- @rfdonnelly made their first contribution in #1438
