### ISSUE TITLE
Kroki.io site seems down (2023-03-08)

### ISSUE THREAD

**Issue by gissehel** [yuzutech/kroki#1457]
As of 2023-03-08, the site kroki.io seems down, at least for the dynamic part (the static home page, the associated CSS, and even the default svg example seems ok, but any change on the editable diagram on kroki.io fails to render).

The error is a "bad gateway" from Cloudflare, with Cloudflare working and kroki.io being down as stated by Cloudflare.
![image](https://user-images.githubusercontent.com/199364/223786714-fcf9a94c-3ec6-4b5e-bb0e-68bdb037babb.png)

Also the error was seen on both my personal ISP and my professional access.

**Comment by PierreR** [comment]
I can confirm the issue.

**Comment by ggrossetie** [comment]
Indeed, something is wrong 🔥 🧑‍🚒 

![image](https://user-images.githubusercontent.com/333276/223794691-d3464377-911d-43f6-aeb9-eddb4602f916.png)

**Comment by ggrossetie** [comment]
Should be better now, I will investigate 🕵🏻 
Thanks for the heads-up!

**Comment by deining** [comment]
As you can see at the [Try](https://kroki.io/#try) section at `kroki.io`, there are  issues with other diagram types, too:

- RackDiag
- SeqDiag
- NWDiag
- ???

![grafik](https://user-images.githubusercontent.com/18169566/223975770-7b0616b0-d1d4-4aa9-ac00-4d435259ae5e.png)

![grafik](https://user-images.githubusercontent.com/18169566/223975973-dbfebfa2-fcbe-4cba-a240-0a524a9abc85.png)

![grafik](https://user-images.githubusercontent.com/18169566/223976178-a3c3202f-b478-406e-bcdc-a0ebc11a2330.png)

Thanks for looking into this!

**Comment by ggrossetie** [comment]
@deining @PierreR can you please try again?

**Comment by deining** [comment]
> @deining can you please try again?

For me everything seems to be o.k. again. Thanks for your immediate action!

**Comment by ggrossetie** [comment]
The cause was `java.lang.OutOfMemoryError: Java heap space` at `2023-03-08T10:24:49.667Z`.
I will configure the JVM to heapdump on OutOfMemoryError in order to investigate further if this error happens again. 

I will also try to move PlantUML and UMlet into a dedicated JVM with more aggressive memory settings to improve stability of the gateway server.

**Comment by ggrossetie** [comment]
Yes, but this time I have a `hprof` file to troubleshoot 😉

**Comment by ggrossetie** [comment]
I think I've identified one issue: https://github.com/umlet/umlet/issues/711
