### ISSUE TITLE
GraphViz: 'pdf' output format supported as documented?

### ISSUE THREAD

**Issue by deining** [yuzutech/kroki#1459]
According to this [section](https://kroki.io/#support) of `kroki.io`, `pdf` is supprted as output format for GraphViz:

![grafik](https://user-images.githubusercontent.com/18169566/224011541-cfa9163d-173a-4de8-8d8e-a554deb64c33.png)

However, when trying to retrieve a GraphViz `pdf` resource using this [URL](https://kroki.io/graphviz/pdf/eNp9kM0KgzAQhO8-xZIHaKlX6Ulp6S-FPoDEuGhqbML6cyl594JVGyv1OMPMt8ukMiNucojg5QFUTfKRQjVVjRSbzgZQPEEFW2An0oVkQWfO0mLTx53CHalF6hsAO6kwQV4PesbIRPylOJxIiwJp_YMDOPKWD8ouQP0F6AWp5DJ1qOyqU1w9Kte6NcZgjZPrLMxJl8imH9g_8_jzecLzYSzvteLPLBgR1rNvJ7Rwmw==), I'm getting this error message:

![grafik](https://user-images.githubusercontent.com/18169566/224011975-03e94b7e-0c37-46b3-a7a1-2c2614b9dcfc.png)

Is the documentation incorrect here?

**Comment by ggrossetie** [comment]
GraphViz has a PDF output but it might be unavailable on Alpine. I need to check.

**Comment by ggrossetie** [comment]
And PDF is not enabled: https://github.com/yuzutech/kroki/blob/dfce464ae0264c41ba867e84fc0bcbf5c0d6d934/server/src/main/java/io/kroki/server/service/Graphviz.java#L21

**Comment by ggrossetie** [comment]
I've enabled the pdf output in https://github.com/yuzutech/kroki/commit/f14da288bfd1ae2540155edaab68f47021879123
