### ISSUE TITLE
PlantUML external include

### ISSUE THREAD

**Issue by niceborn** [yuzutech/kroki#1462]
Hello,
perhaps I'm wrong.

I have a installation with environment settings:
- KROKI_PLANTUML_ALLOW_INCLUDE = false
- KROKI_SAFE_MODE = SECURE

If I render the example with external includes

```
@startuml
!define osaPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-opensecurityarchitecture2-icon
!include osaPuml/Common.puml
!include osaPuml/User/all.puml
listsprites
@enduml
```
I get no error message as expected but the rendered image (also on kroki.io):

https://kroki.io/plantuml/svg/eNpdjrEKwzAMRPd8RfIBiaFjp0DWFrLkA1RbrQW2bCSZ0r-vaaFDx7vj7t2qBmItp2EKeCfGsSjsXY_RrOrZOYHn8iCL7dYUxRc2ZFt8yW4T0IghEwe3J2A7rpe5VGRF34TsBeIjGXprgqeZeneYiH1q4YdxW8m58FI_F_7DoxMdpPSNE6lp7cOow4ocuvcG9-lH1Q==

Is this the expected behaviour?

**Comment by ggrossetie** [comment]
PlantUML has built-in "stdlib" which are available inside the jar file.

Kroki will include `osaPuml` from the "stdlib" and won't make any HTTP call or try to read files from the local disk.

**Comment by niceborn** [comment]
OK, so no error is displayed but includes and local or external calls are just ignored? 
When trying this on plantuml.com I get an error "Cannot open URL" instead.

If fist assumption is right, it would be fine for me.

**Comment by ggrossetie** [comment]
That's correct, `!include` and `!define` directives are removed/sanitized from the input.
We use the local "stdlib" when we can to create a better experience for users.

**Comment by ggrossetie** [comment]
Feel free to join https://kroki.zulipchat.com/ if you have additional questions.

The issue tracker is the preferred channel for reporting verifiable bugs, regressions, and security vulnerabilities or for making formal change requests. Whereas the project chat is the preferred means of communication.

**Comment by niceborn** [comment]
Thanks for the hint. I was not sure if this was an issue.
