### ISSUE TITLE
PRs: Docs CI test fails

### ISSUE THREAD

**Issue by deining** [yuzutech/kroki#1470]
Docs CI test currently fails with all pull requests, e.g.:

https://github.com/yuzutech/kroki/actions/runs/4414811022/jobs/7736992707

Can you please have a look and fix that? Thanks.

**Comment by ggrossetie** [comment]
It was a chicken-egg issue where the documentation CI was trying to setup Kroki including `kroki-wireviz` which was not yet published on Docker hub.

This is now resolved ✔️
