### ISSUE TITLE
WireViz container missing ttf-liberation for PNGs

### ISSUE THREAD

**Issue by copyrights** [yuzutech/kroki#1477]
WireViz container is missing ttf-liberation package
![grafik](https://user-images.githubusercontent.com/219009/226121161-28e5ef2b-6dcd-4ae9-ae32-c9c859bd9116.png)

**Comment by copyrights** [comment]
I'm very sorry that I haven't tested it enough in #1439 :disappointed:

**Comment by ggrossetie** [comment]
@copyrights Yep, I noticed this issue *after* releasing 0.20.0. that's why I didn't check `png` in https://kroki.io/
Feel free to submit a pull request to add the missing font 😄 

By default, the font is `arial`, so liberation font should work fine.

**Comment by copyrights** [comment]
already summited in #1478
