### ISSUE TITLE
Build Graphviz from source

### ISSUE THREAD

**Issue by FelixVanOost** [yuzutech/kroki#1483]
The latest version of Graphviz available via `apt` ([2.42.2](https://packages.ubuntu.com/jammy/graphviz)) was first released in September 2019 and is very out of date. From the Graphviz [Download](https://graphviz.org/download/) page, the maintainers note that they no longer provide precompiled packages.

By building Graphviz from source, it should be easy to update to much newer releases (which are made every month or so).

**Comment by ggrossetie** [comment]
Yes this is a good idea but we should build it once otherwise it will slowdown the CI.

**Comment by FelixVanOost** [comment]
For `kroki-builder-erd`, it looks like you included the image commands in the Dockerfile and then commented them out once the image was pushed. Should we follow the same approach here?

**Comment by ggrossetie** [comment]
> For kroki-builder-erd, it looks like you included the image commands in the Dockerfile and then commented them out once the image was pushed. Should we follow the same approach here?

Sounds good, we should have a task to publish a new version of `kroki-builder-*` images. But otherwise, yes we should do:

```
FROM yuzutech/kroki-builder-graphviz:3.0.0 AS kroki-builder-static-graphviz
```

```
COPY --from=kroki-builder-static-graphviz /path/to/dot /usr/bin/dot
```

**Comment by ggrossetie** [comment]
I found pre-built binaries at https://gitlab.com/graphviz/graphviz/-/releases
I will give it a try 😉
