### ISSUE TITLE
excalidraw: newlines in text elements are not working

### ISSUE THREAD

**Issue by Lazzaretti** [yuzutech/kroki#1499]
I try to use kroki 0.20.0 with excalidraw.
Unfortunately, newlines in text elements are not working.

excalidraw:

```json
{
  "type": "excalidraw",
  "version": 2,
  "source": "https://excalidraw.com",
  "elements": [
    {
      "id": "74iZwH3hDND5dcIYMRShJ",
      "type": "text",
      "x": 727.5497278144244,
      "y": 233.29373351334598,
      "width": 62.37994384765625,
      "height": 50,
      "angle": 0,
      "strokeColor": "#000000",
      "backgroundColor": "#e64980",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "groupIds": [],
      "roundness": null,
      "seed": 1819588545,
      "version": 5,
      "versionNonce": 84916495,
      "isDeleted": false,
      "boundElements": null,
      "updated": 1680096038483,
      "link": null,
      "locked": false,
      "text": "test\nnewline",
      "fontSize": 20,
      "fontFamily": 1,
      "textAlign": "left",
      "verticalAlign": "top",
      "containerId": null,
      "originalText": "test\nnewline",
      "lineHeight": 1.25
    }
  ],
  "appState": {
    "gridSize": null,
    "viewBackgroundColor": "#ffffff"
  },
  "files": {}
}
```

## Output of https://excalidraw.com/

![image](https://user-images.githubusercontent.com/7142819/228552724-11ffed80-4235-4953-ae08-e4c0b286ebcb.png)

## Output of https://kroki.io/#try

![image](https://user-images.githubusercontent.com/7142819/228552911-b9a1f7f4-a63a-4d7f-804c-ecde5e1ec5be.png)

**Comment by ggrossetie** [comment]
Thanks for your report, I can reproduce it 🤔

**Comment by Lazzaretti** [comment]
I think the problem lies in excalidraw `exportToSvg()`. 
I created a bug there: https://github.com/excalidraw/excalidraw/issues/6468

**Comment by ad1992** [comment]
Hey  @Lazzaretti this fix is not yet shipped to the npm package, will be releasing the fix very soon, till then you can try by installing`next` version - `yarn add @excalidraw/excalidraw@next` and that should work.
