### ISSUE TITLE
Kroki service not working properly

### ISSUE THREAD

**Issue by deining** [yuzutech/kroki#1509]
Calling kroki service from command line:

```
http https://kroki.io/ diagram_type='graphviz' output_format='svg' diagram_source='digraph G {Hello->World}'
```

I'm getting `504 Bad Gateway` as response.

![grafik](https://user-images.githubusercontent.com/18169566/232067784-f5e62977-5022-40ba-bef4-6ad953b989ab.png)

Thanks for investigating.

**Comment by ggrossetie** [comment]
Should be fixed on main branch. We are now using UMlet, Ditaa and PlantUML as native images.
