### ISSUE TITLE
d2 diagrams: support sketch mode (hand-drawn aesthetic)

### ISSUE THREAD

**Issue by deining** [yuzutech/kroki#1510]
D2 supports a `sketch` mode now. With this mode enabled, diagrams looks like hand-drawn. For details, see this [blog post](https://d2lang.com/blog/hand-drawn-diagrams) and the corresponding [documentation](https://d2lang.com/tour/sketch/) and the corresponding [pull request](https://github.com/terrastruct/d2/pull/492).
Were great if this mode could be supported by kroki. I envision an additional diagram option `sketch` for d2 diagrams that acts as flag: with this option present, diagrams will be in sketch mode.

**Comment by ggrossetie** [comment]
I think we need to update D2 to the latest version and add an new option.

**Comment by FelixVanOost** [comment]
@deining I put PR #1520 together quickly to add this option but haven't had time to test it yet. Feel free to try it out and let me know if it's working as expected!
