### ISSUE TITLE
Pass SSL environment variables as paths instead of strings

### ISSUE THREAD

**Issue by FelixVanOost** [yuzutech/kroki#1512]
The environment variables `KROKI_SSL_KEY` and `KROKI_SSL_CERT` currently store the contents of the key and certificate as strings, which differs from the more common usage in which the file paths are provided directly. The current approach has two drawbacks that I can see:

- The environment variables must be manually updated whenever the TLS certificate is renewed. This is typically every 3 months (e.g., for Let's Encrypt and ZeroSSL).
- The certificate and private key are accessible by any system user via the environment variables or, if defined in a `docker-compose.yml`, anyone with access to the file.

Both of these issues could be resolved by storing paths to the certificate and key in the environment variables instead and mounting a volume containing the files to the main Docker image.

**Comment by ggrossetie** [comment]
I can support this idea if we keep the existing feature as both options have advantages and drawbacks.
For instance, if you declare key and certificats as paths, you will need to make sure that the container has access to these files (i.e., mount a local disk or copy files inside the container).

In my opinion, we should add two new environment variables:

- `KROKI_SSL_KEY_PATH`
- `KROKI_SSL_CERT_PATH`

I think `KROKI_SSL_KEY` and `KROKI_SSL_CERT` should have higher precedence. Also make sure to update the documentation to document this feature.
