### ISSUE TITLE
docker hub is missing manifest for linux/arm64/v8

### ISSUE THREAD

**Issue by lipkau** [yuzutech/kroki#1533]
Hello.

I am unable to `docker pull yuzutech/kroki` on my mac m2.
I get the message
> no matching manifest for linux/arm64/v8 in the manifest list entries

I have searched the repository for similar issues and found #1084 and #1487.
As the PR has been merged, I would have expected the problem to be solved, but seems I am mistaken.

Is this known and is the an outlook for a fix?

**Comment by FelixVanOost** [comment]
The images on Docker Hub are only updated when a formal release is made. The two PRs that added `arm64` support, #1487 and #1523, were merged after the latest release `v0.20.0`, so I expect them to be part of the next release.

In the meantime you can build the images locally from the `main` branch.

**Comment by mariotoffia** [comment]
@lipkau Just build it locally, I had to do `-DskipTests` since tests around Certificates gave me problems. It will build the images locally and it works like charm.

Cheers,
 Mario :)

**Comment by ggrossetie** [comment]
Hello @lipkau 

> I have searched the repository for similar issues and found https://github.com/yuzutech/kroki/issues/1084 and https://github.com/yuzutech/kroki/pull/1487.
As the PR has been merged, I would have expected the problem to be solved, but seems I am mistaken.

Work has been done and merged on the main branch but we have not yet published a new release.

> Is this known and is the an outlook for a fix?

As mentioned above, you can build from sources.

**Comment by ggrossetie** [comment]
Feel free to join https://kroki.zulipchat.com/ if you have additional questions.

The issue tracker is the preferred channel for reporting verifiable bugs, regressions, and security vulnerabilities or for making formal change requests. Whereas the project chat is the preferred means of communication.
