### ISSUE TITLE
Plantuml Azure stdlib not using latest diagram library, works on PlantUML server, not on Kroki

### ISSUE THREAD

**Issue by npiper** [yuzutech/kroki#1534]
The Plantuml Stdlib was recently aligned to version 2.2 of the Azure icons

To avoid using URL includes diagrams they will render better when using the PlantUML Stdlib notation such as 
`!include <azure/AzureCommon>`

Repos:
https://github.com/plantuml/plantuml-stdlib
https://github.com/plantuml-stdlib/Azure-PlantUML

Commit ID that was Upgrading the base version to 2.2 
https://github.com/plantuml/plantuml-stdlib/commit/af8ab9ea3b21f752e2dcc96fbb703946b94e196c

Icons that work in the 2.2 version of Azure icons on Plantuml server don't work on the Kroki server, is it possible to check the Plantuml dependency / version to make sure it gets the latest usage / version of stdlib?

Example PUML Source with Azure 2.2 Icons:

```
@startuml
skinparam linetype ortho
 
!include <azure/AzureCommon>
!include <azure/Security/AzureKeyVault>
!include <azure/Identity/AzureManagedIdentity>
!include <azure/Identity/AzureActiveDirectory>
!include <azure/Identity/AzureActiveDirectoryB2C>


rectangle "Azure IT Security / Identity" {

   AzureKeyVault(keyVault, "Azure Key Vault","Secret / Password Management")
   AzureManagedIdentity(identity, "Azure Managed Identity","Service Account Management")

   AzureActiveDirectory(ad, "Azure Active Directory","IT Identity / SSO")
   AzureActiveDirectoryB2C(adB2C, "Azure Active Directory B2C","IT Federated Identity / SSO")

}

@enduml
```

Expected (Plantuml web server output)
![image](https://user-images.githubusercontent.com/436314/236065799-9c29f804-052b-464d-a569-f3272a2ac86a.png)

Actual kroki.io:

`Error 400: cannot include (line: 5)'

The macro for `!include <azure/Identity/AzureManagedIdentity>` was added in the 2.2 release.

**Comment by npiper** [comment]
Additional commit reference for the 2.2 Merge:
https://github.com/plantuml/plantuml-stdlib/commit/db233ddaa00afa6e4fe6ac4a8de01e332b61bca4

**Comment by ggrossetie** [comment]
I guess it was added in the latest version of PlantUML? kroki.io is using version 1.2022.14 but we are using 1.2023.6 on main branch (next release).

Feel free to join https://kroki.zulipchat.com/ if you have additional questions.

The issue tracker is the preferred channel for reporting verifiable bugs, regressions, and security vulnerabilities or for making formal change requests. Whereas the project chat is the preferred means of communication.
