### ISSUE TITLE
Add OCI annotations to docker images

### ISSUE THREAD

**Issue by mikaello** [yuzutech/kroki#1542]
It would have been nice if the Kroki docker image built in this project used [the OCI annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md), these can be used by other tools to enhance the user experience. E.g. Renovate will use the source label to add a link back to where the image is coming from.

Currently, there are no labels for the kroki image:

```shell
$ docker inspect yuzutech/kroki:0.20.0 --format '{{ json .Config.Labels }}'
null
```

This could be done be adding the OCI labels directly into the Dockerfile, or by using the [docker/metadata-action](https://github.com/docker/metadata-action), but that is maybe difficult since you are building the images inside a Makefile?

**Comment by ggrossetie** [comment]
Behind the scene we are using `docker buildx bake` which supports labels: https://docs.docker.com/build/bake/reference/#targetlabels

It would be useful if you could suggest a list of labels (key and value) that we should set.

**Comment by mikaello** [comment]
Sure!

The one I find most useful is `org.opencontainers.image.source`, which can be used to provide a reference back to this repository. But it could be nice some of the others as well:

```Dockerfile
LABEL \
    org.opencontainers.image.title="Kroki" \
    org.opencontainers.image.description="Kroki provides a unified API supporting multiple diagramming formats, making it easy to create diagrams from textual descriptions." \
    org.opencontainers.image.url="https://kroki.io" \
    org.opencontainers.image.source="https://github.com/yuzutech/kroki" \
    org.opencontainers.image.licenses="MIT"
```

But you maybe want to use the `labels` map field in [docker-bake.hcl](https://github.com/yuzutech/kroki/blob/main/docker-bake.hcl)?

**Comment by ggrossetie** [comment]
Thanks!

> But you maybe want to use the labels map field in [docker-bake.hcl](https://github.com/yuzutech/kroki/blob/main/docker-bake.hcl)?

Is there a best practice or a recommended way to define labels?
Since the values are "static" (i.e., do not depend on the context/release) I would say it's fine to define them in the Dockerfile.

Are you willing to submit a pull request?

**Comment by mikaello** [comment]
> Is there a best practice or a recommended way to define labels?

I'm not sure, the docker bake file was new to me, I am only used to pure Dockerfiles.

> Are you willing to submit a pull request?

Absolutely :-) https://github.com/yuzutech/kroki/pull/1545
