### ISSUE TITLE
Exec format error for BPMN, Diagrams.net, and Excalidraw on arm64

### ISSUE THREAD

**Issue by FelixVanOost** [yuzutech/kroki#1547]
The latest versions of the BPMN, Diagrams.net. and Excalidraw companion images (`v0.21.0`) return an `exec format error` when attempting to run them on an `arm64` machine. For now, the `v0.20.0` companion images seem to work fine with the latest main image.

This is due to a missing environment variable I forgot to add in #1487.

**Comment by FelixVanOost** [comment]
I've opened #1548 to fix this.

**Comment by ggrossetie** [comment]
@FelixVanOost new version published on https://hub.docker.com/. Could you please check that companion containers avec working fine on ARM64?

**Comment by FelixVanOost** [comment]
@ggrossetie All the `v0.21.2` companion containers are working now. 😀
