### ISSUE TITLE
Support for alternate layout engine(s) in D2

### ISSUE THREAD

**Issue by eikef** [yuzutech/kroki#1557]
Currently, D2 diagrams are rendered with the Dagre layout engine. D2 supports multiple different layout engines (among them a commercial one, but that's beside the point and quite probably out of focus for Kroki); there is at least one other FOSS engine available named ELK which may produce superior output depending on what your type of input is. It appears to be immediately usable after installation (with the `-l elk` parameter)

This could be supported via an option just like different themes are supported today.

**Comment by ggrossetie** [comment]
That's a good idea! Do you want to give it a try?
