### ISSUE TITLE
PlantUML, C4PlantUML and GraphViz low quality on PNG format

### ISSUE THREAD

**Issue by yoopyman** [yuzutech/kroki#1565]
When trying to generate the graphviz/dot diagrams with PlantUML or C4PlantUML or GraphViz  
in the PNG format the image looks like this : 

![image](https://github.com/yuzutech/kroki/assets/121875047/5ac97e74-6c65-40a4-af7b-bfe63efc78ac)

generated with link: 

https://kroki.io/graphviz/png/eNp1kMFOwzAQRO_9isV3-IBGgQsSnBBXFHrYxkti1V1btkNVVf13vHGTVkG92TOeyZto0wX0PbzBaQXAThM0P44T456gBvWOrC2R2lTZJt3dt7OvAx6gyQcAi1uy8uJVNARv2jQEUtXoxh695AO1SZSx_WB4Gf5yg8gPi5j7RTvHuoFi_PdVoyH1dPzmYpv0sujQBveO9VzjneG0rPkcxUCeMJG2uS456YUo-y-bnu6Pmv7J43PBnGZOd2hutlJUVcYK9Rbb3Q3UOs7v1_G6OGsX5mvHh1MleBqJAvKuFtQCWBBKqhIOkc-r8x9lvpbL

When the same diagram is generated as SVG it looks like this: 

![image](https://github.com/yuzutech/kroki/assets/121875047/56552ade-aa4a-410d-b0b2-df3f680c1336)

generated with link:

https://kroki.io/graphviz/svg/eNp1kMFOwzAQRO_9isV3-IBGgQsSnBBXFHrYxkti1V1btkNVVf13vHGTVkG92TOeyZto0wX0PbzBaQXAThM0P44T456gBvWOrC2R2lTZJt3dt7OvAx6gyQcAi1uy8uJVNARv2jQEUtXoxh695AO1SZSx_WB4Gf5yg8gPi5j7RTvHuoFi_PdVoyH1dPzmYpv0sujQBveO9VzjneG0rPkcxUCeMJG2uS456YUo-y-bnu6Pmv7J43PBnGZOd2hutlJUVcYK9Rbb3Q3UOs7v1_G6OGsX5mvHh1MleBqJAvKuFtQCWBBKqhIOkc-r8x9lvpbL

At the same DPI the image are different. This problem appeared in the latest version.
On windows using the version 0.20.0 this problem is not present. On the 0.20.0 the SVG and PNG image are identical.
Maybe the engines (or the format converter if used) needs some additional configuration regarding the quality or some antialiasing when transforming to PNG to eliminate this issue.

**Comment by ggrossetie** [comment]
We are using the latest version of GraphViz. I will need to investigate why the quality is different.

**Comment by ggrossetie** [comment]
Will be fixed in https://github.com/yuzutech/kroki/pull/1568

| 8.0.4 | 8.0.5 |
| --- | --- |
|  ![804](https://github.com/yuzutech/kroki/assets/333276/1cd622d5-21dd-46cc-8f25-394bdb673382) |  ![805](https://github.com/yuzutech/kroki/assets/333276/43d6551d-37f5-4b71-8643-8384e65bd541) |
