### ISSUE TITLE
Cannot render plantuml diagram with AWS icons using Kroki latest version.

### ISSUE THREAD

**Issue by ghilainm** [yuzutech/kroki#1601]
Here is a plantuml snippet which works fine with plantuml directly but generates an error with Kroki.

(https://www.plantuml.com/plantuml/uml/jP8_JyCm4CNtV8hG2IIIemi3KqlvCm1Yo53MYtEq1liS-Swj2kAxaz2IjK8e7iv-jlH-pwURYMBKv5rsOjcur52-Lctb2Y3YjbnPNQSw2KKJM8crDC43RiLXBVrUsEv1YjSGYzOXzqwmcLwM5z1OKPWlgqNmFd3PZiRe06rIWaVqTOEZWbZHCaM1MuUYrWmt5SMDDJJewOWnAWqHLmILzQsZWpe4k4xcdNJP4PxhDp8g8-QOCxgTMYFmO9d4oWqgLXe9_PZO9sHSaIVM-x2XoCY6OE52QfQePhqd_mKzG7uFXMZZR0qUHIa2VgH8CE_hyLd-1w5lNur2icVryWwDXhWx_AcpQWCJQ_wIVsPvjuwEuIcUvnES_9Ipx2kR4JUTrpS0)

I can see the following error message in the console when using the docker container locally:

"An error occurred"
"Could not create font BlinkMacSystemFont, -apple-system, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Fira Sans', 'Droid Sans', 'Helvetica Neue', 'Helvetica', Arial, sans-serif"

```
@startuml

!include https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v16.0/dist/AWSCommon.puml
!include https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v16.0/dist/Compute/Lambda.puml
!include https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v16.0/dist/Containers/ElasticContainerServiceContainer1.puml
!include https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v16.0/dist/Storage/SimpleStorageServiceBucketWithObjects.puml
!include https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v16.0/dist/Analytics/KinesisDataStreams.puml
!include https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v16.0/dist/ManagementGovernance/CloudWatch.puml

!include https://raw.githubusercontent.com/plantuml/plantuml-stdlib/master/azure/AzureCommon.puml
!include https://raw.githubusercontent.com/plantuml/plantuml-stdlib/master/azure/Databases/AzureDataFactory.puml

component X {
    ElasticContainerServiceContainer1(a, "a", "a")
}

@enduml
```

**Comment by ggrossetie** [comment]
Did you configure the safe mode as mentioned in: https://docs.kroki.io/kroki/setup/configuration/#_safe_mode
