### ISSUE TITLE
Error with diagramsnet, when using parameters

### ISSUE THREAD

**Issue by Heiss** [yuzutech/kroki#1602]
Hey,

as i mentioned [here](https://github.com/ggrossetie/asciidoctor-kroki/issues/424), i got an error when using a parameter in addition with diagramsnet.

Example:
I created a diagram with diagrams.net online editor:
![image](https://github.com/yuzutech/kroki/assets/52699794/fcc517be-4d0e-41e2-999a-f117747da1ed)

The following url (generated by https://kroki.io/#how)
```
http://localhost:8080/diagramsnet/svg/
eNp1U11v2kAQfOdXrO4pkYrtM8ZAiJESIkGbkFYxKhVvV_vAR84-53wOmF_f9UeDIrXyg3dvbtc7M-vb9LQTkkOiChMQludWLNhes7SwMm4IpCoWO8HjgLiOO-g7o747XjvjG-reeL418eiWANvzDItX6iykZPbQcuBqI7JYHQt4XgN1LGcKeOB7Uzj53jXc5bnkG_77URh7OBhZAx-uHpfr1dMXkOKVw4JHr-oa5olWKbcp9SynfiBkO6ZFV0KAG7YPyGb-8EwXx8PbbrTcVZPkPvqaEHjnuhAqw7Gp5VtDAqbKeUBi_i4iTmY9gNuOKGQsReQHsuhTAgKprr95i3DklueXstxGg7s3JwybGqxKTwvN8mSlYi4hPtW6-B6BuAoIdSbYYK_rFl0QijOvAcxKEfOiAYxS0oi8TSKVZTwyTcy0Rs2acKdk2yXHuT6CMGLykm1EbJKAjIdOmy-52Cd1J-rgScpqEIMiYWhFHbYUkIRWyvxNGk5zLmVDHe_b_0aaj-rG6f9fekrv5w-HX7L46Y3z7eGl8r_Tvot2MFni4Eu8p2CjtIxxLlPVZLQqsxgXzJkeE2F4mLOIB0fUeJqYVAZ02php-OnTCJRcBmhd4bgrRleA9wY-ToiGDAf4PrYqURfjpFOoxhkKve-KPvOxW0IfatkXuWrs4n-zRna3R7NeDdY_06z3B2oZ9vY=
```

is working as expected and returns

`<svg xmlns="http://www.w3.org/2000/svg" style="left: 0px; top: 0px; width: 100%; height: 100%; display: block; min-width: 122px; min-height: 62px;"><g><g/><g><g transform="translate(0.5,0.5)" style="visibility: visible;"><rect x="1" y="1" width="120" height="60" fill="rgb(255, 255, 255)" stroke="rgb(0, 0, 0)" pointer-events="all"/></g><g style=""><g><foreignObject pointer-events="none" width="100%" height="100%" style="overflow: visible; text-align: left;"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 118px; height: 1px; padding-top: 31px; margin-left: 2px;"><div data-drawio-colors="color: rgb(0, 0, 0); " style="box-sizing: border-box; font-size: 0px; text-align: center;"><div style="display: inline-block; font-size: 12px; font-family: Helvetica; color: rgb(0, 0, 0); line-height: 1.2; pointer-events: all; white-space: normal; overflow-wrap: normal;">Hello World</div></div></div></foreignObject></g></g></g><g/><g/></g></svg>`

But if i add a query-parameter to the same url:

```
http://localhost:8080/diagramsnet/svg/
eNp1U11v2kAQfOdXrO4pkYrtM8ZAiJESIkGbkFYxKhVvV_vAR84-53wOmF_f9UeDIrXyg3dvbtc7M-vb9LQTkkOiChMQludWLNhes7SwMm4IpCoWO8HjgLiOO-g7o747XjvjG-reeL418eiWANvzDItX6iykZPbQcuBqI7JYHQt4XgN1LGcKeOB7Uzj53jXc5bnkG_77URh7OBhZAx-uHpfr1dMXkOKVw4JHr-oa5olWKbcp9SynfiBkO6ZFV0KAG7YPyGb-8EwXx8PbbrTcVZPkPvqaEHjnuhAqw7Gp5VtDAqbKeUBi_i4iTmY9gNuOKGQsReQHsuhTAgKprr95i3DklueXstxGg7s3JwybGqxKTwvN8mSlYi4hPtW6-B6BuAoIdSbYYK_rFl0QijOvAcxKEfOiAYxS0oi8TSKVZTwyTcy0Rs2acKdk2yXHuT6CMGLykm1EbJKAjIdOmy-52Cd1J-rgScpqEIMiYWhFHbYUkIRWyvxNGk5zLmVDHe_b_0aaj-rG6f9fekrv5w-HX7L46Y3z7eGl8r_Tvot2MFni4Eu8p2CjtIxxLlPVZLQqsxgXzJkeE2F4mLOIB0fUeJqYVAZ02php-OnTCJRcBmhd4bgrRleA9wY-ToiGDAf4PrYqURfjpFOoxhkKve-KPvOxW0IfatkXuWrs4n-zRna3R7NeDdY_06z3B2oZ9vY=?id=testref
```

it returns

`Error 400; Internal server error`

I would expect, that it ignores the parameter and returns the same data as before.
I hope, my example clarifies the error. Thank you for your support.

Heiss

**Comment by ggrossetie** [comment]
You can take a look at how we handle things on the Mermaid service:
 https://github.com/yuzutech/kroki/blob/main/mermaid/src/index.js#L28-L29

**Comment by Heiss** [comment]
Hey, that was easy. I think this issue was there with mermaid, too. So i copied the workaround from there. In the local docker setup, it fixes the issue.
Thank you for your fingerpoint.
