### ISSUE TITLE
plantuml stores diagram source code in PNG by default

### ISSUE THREAD

**Issue by Kinokin** [yuzutech/kroki#1610]
from plantuml documentation:

> After all preprocessing (includes etc), PlantUML saves the diagram's source code in the generated PNG Metadata in the form of encoded text.
> 
> If you does not want plantuml to save the diagram's source code in the generated PNG
> Metadata, you can during generation use the option -nometadata to disable this
> functionality (To NOT export metadata in PNG/SVG generated files).

This is causing an unexpected information leak for kroki users

Please add an option to kroki to enable the opt-out '-nometadata'

**Comment by ggrossetie** [comment]
Since diagram options are supported it's a matter of passing this option in: https://github.com/yuzutech/kroki/blob/22558e0f599db4963f82e2526cd45d387dbaade6/server/src/main/java/io/kroki/server/service/PlantumlCommand.java#L70-L88

We might want to support both `nometadata` and `no-metadata`.

**Comment by ggrossetie** [comment]
@FelixVanOost it makes sense but I think you should bring this proposal to PlantUML. Kroki can be opinionated but I would prefer a common consensus.

**Comment by FelixVanOost** [comment]
I have no strong opinion on this so I can also easily add a `no-metadata` argument instead for consistency with PlantUML. The philosophical question is more around whether Kroki should try and make all the diagram libraries act as consistently as possible or follow their original author's behaviour as much as possible.

**Comment by Kinokin** [comment]
Thanks for the diagram option.
Still not sure how to enable this option as default for a kroki instance

**Comment by ggrossetie** [comment]
> Still not sure how to enable this option as default for a kroki instance

There's no global configuration but you can add `?no-metadata` when using the `/plantuml/png` route. We could introduce a concept of global configuration but that would be another feature/issue.
