### ISSUE TITLE
Update Docker base images to remove high severity vulnerability

### ISSUE THREAD

**Issue by asos-robbell** [yuzutech/kroki#1627]
Node 18.16.1 includes a high severity vulnerability reported by Snyk. Updating base images to 18.17.1 removes this vulnerability.

https://security.snyk.io/vuln/SNYK-UPSTREAM-NODE-5848038

Happy to open a PR for this if that helps.

**Comment by ggrossetie** [comment]
I believe there's already one PR: https://github.com/yuzutech/kroki/pull/1596

According to the CVE this vulnerability affects `process.binding()`:

> Affected versions of this package are vulnerable to Arbitrary Code Injection. The use of the deprecated API process.binding() can bypass the policy mechanism by requiring internal modules and eventually take advantage of process.binding('spawn_sync') run arbitrary code, outside of the limits defined in a policy.json file.

https://security.snyk.io/vuln/SNYK-UPSTREAM-NODE-5848038

Since we are not using `process.binding()` I think we are pretty safe.

**Comment by heyLu** [comment]
This issue can probably closed as the PR with the update to 18.17 (#1596) has been merged?

**Comment by ggrossetie** [comment]
Indeed, closing 🚪
