### ISSUE TITLE
Not all structurizr autolayout directions work

### ISSUE THREAD

**Issue by sixtysecrun** [yuzutech/kroki#1633]
According to **structurizr** DSL [documentation](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#autoLayout) of `autolayout` property it supports four possible directions:

- `tb`: Top to bottom (default)
- `bt`: Bottom to top
- `lr`: Left to right
- `rl`: Right to left

Indeed all four of them work when using https://structurizr.com/dsl but only two of them works when using [kroki](https://kroki.io/#try)

<details><summary>DSL</summary>
<p>

```
 workspace {
    model { 
        user = person "User" 
        softwareSystem = softwareSystem "Software System" { 
            webapp = container "Web Application" { 
                user -> this "Uses!!!" 
            } 
            database = container "Database" { 
                webapp -> this "Reads from and writes to" 
            } 
        } 
    } 
    views { 
        container softwareSystem { 
            include * 
            autolayout bt
        } 
        theme default 
    } 
}
```

</p>
</details> 

| direction | structurizr | kroki |
|--------|--------|--------|
| `tb` | ✅  | ✅  |
| `bt` | ✅  | ❌ |
| `lr` | ✅  | ✅  |
| `rl` | ✅  | ❌  |

`bt` and `rl` are ignored by kroki

Here is a comparison of structurizr and kroki for `autolayout bt`

![bottom_top](https://github.com/yuzutech/kroki/assets/140757598/fb2a9dc8-c1fe-4484-a37f-d2924a2482c6)

**Comment by ggrossetie** [comment]
We are using the PlantUML exporter and this is probably a limitation: https://github.com/structurizr/export#diagram-notation
