### ISSUE TITLE
plantuml: png sequence diagram error (with graalvm build)

### ISSUE THREAD

**Issue by thomasgl-orange** [yuzutech/kroki#1637]
Just to track this issue on kroki itself... See details in PR https://github.com/yuzutech/plantuml/pull/38 - rendering this diagram as png produces an error (svg works fine) :
```
Bob->Alice: Hello
Bob<--Alice
...
Bob->Alice: Hello again
Bob<--Alice
```
https://kroki.io/plantuml/png/eNpzyk_StXPMyUxOtVLwSM3Jyedyyk-y0dUFC3Hp6emB-KgqFBLTEzPzkNUBAN4_FTU=

It can be solved in the plantuml native build, by adding one more use-case to the graalvm configuration training.

**Comment by ggrossetie** [comment]
Thanks for your contribution!
It will be fixed in the next release: https://github.com/yuzutech/plantuml/releases/tag/v1.2023.10 (assets have been updated)
