### ISSUE TITLE
blockdiag removed?

### ISSUE THREAD

**Issue by oupala** [yuzutech/kroki#1639]
I can see that merge request #1613 remove the support of `blockdiag` schemas by removing the `blockdiag` companion.

@ggrossetie Can you please explain what has changed and why?

Thank you.

**Comment by ggrossetie** [comment]
We are using Zulip to chat. Please join https://kroki.zulipchat.com/


We are now using a single executable (produced by Nuitka) for BlockDiag which is included in the base image.

**Comment by oupala** [comment]
Thank you for the answer.

I think the information should be somewhere in the documentation.

**Comment by ggrossetie** [comment]
It's part of the release note, see "Breaking changes": https://github.com/yuzutech/kroki/releases/tag/v0.22.0

**Comment by oupala** [comment]
Oups, I missed that important source of information. Thanks for pointing that to me!
