### ISSUE TITLE
Add support for Gantt charts

### ISSUE THREAD

**Issue by kabo** [yuzutech/kroki#164]
Love this project! I would like to be able to use it to generate Gantt charts as well though.

**Comment by Mogztter** [comment]
Hi @kabo and thanks for you kind word :blush: 
Did you try Gantt diagram with Mermaid? https://mermaid-js.github.io/mermaid/#/gantt

And here's the result: https://kroki.io/mermaid/svg/eNpdTcsKwjAQvPsV8wENJLGn3ApBTz3pxeNiYg3aFNL9f8yjUnRYWHYeOxNF5gMyOPDbY8C5MLCBpkRzVRyxPy1pJgZuGWIchbVVWv2dwxJxabtyA5jWF3YYUh20VL2QKk-Ho3TNGRd--rT7DT0436SAknA_HZu7cteSCLFoW8f3v9Ilq3TL0n8DDHTvPoXCQLE=

We should probably add an example in here: https://kroki.io/examples.html

**Comment by kabo** [comment]
Oh, nice! I wasn't aware that mermaid supported it :)

**Comment by Mogztter** [comment]
Closing this issue, I will add an example on the website: https://github.com/yuzutech/kroki.io/issues/12
