### ISSUE TITLE
Consider moving k8s yamls into seperate folders

### ISSUE THREAD

**Issue by TeCHiScy** [yuzutech/kroki#1640]
I'm using kroki with k3s, and I followed instructions as stated in [docs](https://docs.kroki.io/kroki/setup/use-kubernetes/).
I found that the yamls used in k8s deployment is maintained as a zip file at [kroki-k8s-multipod.zip](https://github.com/yuzutech/kroki/blob/main/docs/modules/setup/attachments/kroki-k8s-multipod.zip).
However, it doesn't keep up to date with kroki updates, i.e, in kroki 0.22.0, yamls for blockdiag is not needed.
So I suggest to move these k8s yamls into a folder instead of putting them in a zip file, and adjust the CI to publish them as a asset of a release.
Moreover, if we can publish these yaml as a helm chart, that would be nice.

**Comment by perfectra1n** [comment]
You can use Renovate for the time being to keep the containers in your pods up to date @TeCHiScy.

**Comment by TeCHiScy** [comment]
Close as duplicated to #1176. 

However, I think there need a document that mention the helm deployment method. 
And it may be nice to put these yamls directly in the repo, instead of zip them. In this way, yamls would be easy to update, and one can deploy the yamls using `kubectl apply -f <URL>` directly.
