### ISSUE TITLE
Migrate the CI and release to GitHub Actions?

### ISSUE THREAD

**Issue by Mogztter** [yuzutech/kroki#165]
This is a proposal to migrate the CI and the (future) release job to GitHub Actions.
A few benefits:
- Better integration
- Faster startup/build time (I've seen build time improvement on multiple projects)
- macOS, Windows and Linux support on the same platform
- ... ?

A few drawbacks:
- Platform/vendor "lock-in" (ie. put all your eggs in the same basket)
- ... ?

Also Travis builds status don't show up on pull requests anymore for the past few days!

@groovytron Do you have an opinion on it?

**Comment by groovytron** [comment]
I think we can give it a try so that we move all the tools to the same place. And if it's faster and more stable at the moment it's also a good point.

If we have to bring it back to Travis, you will just have to enable the repository in Travis' again and put back the `.travis.yml` file so it's not a big deal.

Would you like me to try it and make a pull request between today and wednesday for that or do you want to take care of it?

**Comment by Mogztter** [comment]
> If we have to bring it back to Travis, you will just have to enable the repository in Travis' again and put back the .travis.yml file so it's not a big deal.

You're right.

> would you like me to try it and make a pull request between today and wednesday for that or do you want to take care of it?

Please feel free to work on it, that would be greatly appreciated :pray:

**Comment by groovytron** [comment]
I got something working but the tests take 21 minutes to be run completely against 15 minutes on Travis CI.

I haven't checked if some optimizations could be done so I'm going to investigate if I can shorten the build time.

The GitHub Actions results in my fork are accessible here: https://github.com/groovytron/kroki/runs/606295638?check_suite_focus=true

Thanks in advance for your feedback.

**Comment by Mogztter** [comment]
> The GitHub Actions results in my fork are accessible here: https://github.com/groovytron/kroki/runs/606295638?check_suite_focus=true
Thanks in advance for your feedback.

Many thanks that's really good! :clap: 

> I got something working but the tests take 21 minutes to be run completely against 15 minutes on Travis CI.

15 minutes and 43 seconds :wink: 
But indeed it's slower! However, I believe that the start is faster on GitHub (ie. before the job is actually running).
The "Install python 3.8.1" step is taking a lot of time... I think we should move the Python part in a parallel job:

1. Install Python
2. Install requirements (locally)
3. Run unit tests

We don't need the above steps to build the Docker image, so it should be safe to run in a separated job. What do you think?

**Comment by groovytron** [comment]
As for the automatic release, it might be a bit more complicated than the testing. I'm not fond of releasing without a human confirmation that triggers the release. And unfortunately GitHub Actions does not offer manual triggerable actions at the moment.

But maybe you have another opinion about that @Mogztter ?

**Comment by Mogztter** [comment]
Sorry about that, this issue is probably too broad, I think we should treat the release automation in another issue.
I will close this issue and open a new one to specifically address "release automation".

> As for the automatic release, it might be a bit more complicated than the testing. I'm not fond of releasing without a human confirmation that triggers the release. And unfortunately GitHub Actions does not offer manual triggerable actions at the moment.

Usually, I trigger a release by pushing a tag then the whole release process is automated (no manual step or confirmation). So it's not a continuous delivery/release because we still have to tell when we want to release (that's my confirmation step).
Did you have something else in mind?

**Comment by groovytron** [comment]
> I will close this issue and open a new one to specifically address "release automation".

I share your point. A new issue about release automation can be created and we can close this one.

> Usually, I trigger a release by pushing a tag then the whole release process is automated (no manual step or confirmation). So it's not a continuous delivery/release because we still have to tell when we want to release (that's my confirmation step).
Did you have something else in mind?

Creating and pushing a tag is a manual action so it looks like a good solution to me. :+1:

**Comment by Mogztter** [comment]
Closing, thanks again for your work @groovytron
