### ISSUE TITLE
excalidraw companion server not using local assets

### ISSUE THREAD

**Issue by gerlingsm** [yuzutech/kroki#1651]
Hello everybody,

this is my first issue so sorry if I missed something in the first place.

I have noticed that in newer versions the excalidraw companion server is not functional if the server or docker container have no public internet access.
I am getting the error message: "TimeoutError: Unable to convert the diagram: Navigation timeout of 30000 ms exceeded TimeoutError: Navigation timeout of 30000 ms exceeded at LifecycleWatcher._LifecycleWatcher_createTimeoutPromise (file:///usr/local/kroki/node_modules/puppeteer-core/lib/esm/puppeteer/common/LifecycleWatcher.js:154:12)"

I have (hopefully correctly) evaluated that this happened between version 0.19.0 and 0.20.0 and affect versions from 0.20.0 or higher.

I have searched online and found that excalidraw is using a public cdn per default but it is changeable by a variable.
(https://docs.excalidraw.com/docs/@excalidraw/excalidraw/installation)
However, the variable "window.EXCALIDRAW_ASSET_PATH" is not set in the docker container.
So for testing i added the line manually inside the docker container to the file /usr/local/kroki/assets/index.html right after "`<body>`" as "<script>window.EXCALIDRAW_ASSET_PATH="excalidraw/"</script>"
I am unsure if this is the right place to post but I can say that after that change and a restart of the docker container, everything is working fine and I no longer get the TimeoutError mentioned above.

Maybe this issue is related to #1529 and the following topic on zulip: https://kroki.zulipchat.com/#narrow/stream/232085-users/topic/Excalidraw.20error

Best regards
Max

For the record the index.html which is working for me:

```
<!doctype html>
<html>
<body>
  <script>window.EXCALIDRAW_ASSET_PATH="excalidraw/"</script>
  <script src="./excalidraw/react.production.min.js" charset="utf-8"></script>
  <script src="./excalidraw/react-dom.production.min.js" charset="utf-8"></script>
  <script src="./excalidraw/excalidraw.production.min.js" charset="utf-8"></script>
</body>
</html>
```

**Comment by ggrossetie** [comment]
Interesting... Could you please submit a pull request with your change? Thanks!

**Comment by gerlingsm** [comment]
yes, i will submit a pull request asap.
But i have to add something, which i didn't see before:
When the "window.EXCALIDRAW_ASSET_PATH" is set, the links to the fronts are also replaced.
This is the desired behaviour.
For example the [kroki original example for excalidraw](https://kroki.io/excalidraw/svg/eNrVm1tT4koXhu_nV1h8twO7z4e58zioM3hARd01ZQUSIBoSTAKIU_Pfv05kk4OJBiVjjFVi0t3pTudhvWutbn9_2dio-fOxUfu2UTMeeppl6q42q30Nrk8N1zMdWxWh8NxzJm4vrDn0_bH37Z9_ohaNnjN6amVYxsiwfU_V-1edb2z8Dn_H-nGNnq_ZA8sIG4RFUVeQ0_TVlmOH3SIuMSEAiGUF09tR3fmGrkr7muUZUUlwqYaur4aIGDoSewdgvltv46vWVdRr37Sstj-3np5J6w0nbmxMnu86d0bH1P1hMK7U9WU7z1EzELVynclgaBuel2jjjLWe6c-DawAsrz5NwreN6MqDOqMiOg9bEJDqe9uxHDfo-38gPKLeu1rvbqCGYOtRHUg1rduP6swWTxTrZmiYg6Ef9CUbMnGwqGsjnGaKoISMUrQsCPob7-vhC_-VnqWh5o4Xs1HzgpPYWINh7j7Rsmi-KFKFWwaco_nj8AJf68SebbvOzY2oLcp_hZ9_vr4Fr9hTp_CCjHBBMGeF8eoegaMLn434D2d2Nb5HyDje3qw6XoytFy_SY0afPscLojfxBTHACDAJSLmAHWrbR7J-cntu2O359mSi2c6ZsxbAcL79ggLy2IO9xtftI2hO7mXdY-PWw84MnN43e6dV54uv2Xz1tS4AWXy9zX4JBiVDcThLwYsTsz-6H03AtAVah-AG7M2OR-vAS6JcvCDCShzpCoCd26PW2Wh24I_YyJl0e9_99mCr6oBJtm7AKKJoXfqIOBeQ0LL5glMGWrs7qOea37_XZ46sOyc_1sAXArl8QYGwejSAivPl9Dk7IJ2jg6bdNMEPBi88_6bqfEFA1gtY1yBdvbs2CwaJZFwyEfODS0Hs9nZy_Dg_tY2fU9xn1Bp7N0xbiwnLVUhlwQgDiJPiiLWtaffWuKhL67Lbc61Ds1sf3lYeMYTWi5hgwpDsOWLsbYRJLASj6qdcwujJyeNwdjO5v7txt7QOmv10zbNihPnGg58Fl4C5bEEhJIAQycJsTV3dxwf97g66nD2SQ3LWaff2q86WSFmvOisHLSgz2CI0w1pJBDkSpVirqHnfsf22-RjMB2aJq3vayLTmifkM6VEdHGhTra0kdOzH58AzLNMOb4QSLTYtcxAwVrOMfhI-3-xp1rLYd8a1F-HVXNeZZdGLSb5pxComYhTI4uFpdgxd9eyH5A0KOMUYK39DSUECZiRlKTCTLDuJZRpmxhiiiXdQmOVwIAVZ9nzN9bdMWzftgSr5HVnMvtObBJXroEGgDCZJOQKCcEzk8psXjEobx19AlJXbf3L7Hwb-9HxL2z-2dzoH1_Lu_KS5TK78WQ7DsPXXBgFTBy4-iOzc3LNBjB0znkwMjuivjQie8GT596-vmbXrMAUXFvH2dSpfuwNCDSIRUSBAzjiiDCVuoJiJ7vAldaeapXn-tjMamb760h4HD6aey55YVvLNbwbmYWhoerpUvZB42cKOrFknlZlRVMkV0mDZOH2yLCsG5cikJEVUUhCGlLslPjKp-j4p3TP83vCvquiLQQbLTfMKyRGkJPb6X-O7_uMeaIPbzgmGZ6c3m1N6TZqdyvON1uoG-q5me2PNVVhlZEqyUr00HtI8Ua5ECjJKMKps4JrrmVHM89cNEJNEqsiiMFHZyeeqJ3YRbAAqBA1iRghiK0Dz8AvXgJxLQKhgyk-ltJygIzECSFGGdeWyIVR8LSlRaozJc2PLMFexrXgLhu_w4tJK_qJrBYr7UdmLUGX7UbnvIThw-g288348_35V9rHiFiFlM7ByPwSGsXDvNZNBhrtHutWbHbLN5vxieNur_7xsf7a1RlRSKgLgIk4WpghCJgWpYCbiWHM9oxpJCIpJHrZSYKqMvCyudNnrYJVPocEGo5wok4OI-oRJiGFJOQjcgBQi5Z9iNUQMZIZPJZXIEikkQ1ICicHzdJtQwS0hWKKPTlGAhpo9qAy2QJyr5xFshQzFIfGcuub2XXBwCVoHD2Kq87M3ZSgQZBhwrnqXWM0aKz6G7NX30oU1AR6iiQQFfK29ApdINdVCAEYUSowk8xsizc9nUVLxQlqfcuU8sOJLRtlwVV1KU2l9VJKWYsaKaClXDjRVnH7oNor3Sa5ie2xaxoZm6xtHY98cBTeohAJzmb-KxRHhDApSfBNk9laBT7bJA5eEe-YSPHuWuYCcKXus4hJRgcy_UjSuRI0xBJRQgBUkTZ-alxO903owm1cnP6_7982O11xdVpW0cyYRjn7DFRYfMvcclSurIlG9Tl5tQJINFBGfRChlru9OuPLdCVvBcGTTUvks1d8xHEQUSuxDKQSSwbx_5H6w9wnlqVF3FvoYiuWO4VRLLkG-dygog5SssGienTyu-n4imPIORTnQZ-X5M8WSqwgEV0IsMUAw2NYPpXJXcXy59j-hIg0BAIGUY8lV8E1QnnLdD-9up_vwYtS51u3D6Tk9Obw-fIt6qr6EVPaYCYKCRLoorp7ZOypLDkpRoj56tUGi-meRTgTzN-7DIDtN0ApmJJuVyu98Fel8bQNKSdWjM_U1AoiVk77FsoiUIhhYclL6f4a8vHz4PindfTB6E78yupm7pkkJFojHg7DXgM_ey_nZ9uEi8veEUzwTTgSopIxIzD4-eavUEGJAMOFCffnF8yAzVya3WX_-eDZAe83NkXt61d--OWuO3iKTOHUUV8nsTeHlqiRaNcZMNRCfRSdRrtVAACDMCcTFdTIblsq72-zvJGOj7P-LMSajSpspJOQjt-u_Txi_b5ejiV8WI6tp43Hb13xjaWxqU9OYbWX9P1h4LO6uZtLUF08TOr5_vvz5PwWZbjk=) is using "Virgil" and "Cascadia" as fonts and loading them from https://unpkg.com/@excalidraw/excalidraw@0.15.2/dist/excalidraw-assets/
With window.EXCALIDRAW_ASSET_PATH="excalidraw/" set, the url is changed to "excalidraw//dist/excalidraw-assets/".
It is relative to the basepath, so with a standard kroki installation it will try to load the fonts from https://example.com/excalidraw/svg/excalidraw//dist/excalidraw-assets/Virgil.woff2 which results in an 404 error from kroki.
In my case this is not a problem. I am using an Apache2 reverse proxy before kroki so i can exclude this specific url from proxy pass.

Maybe it's possible to make a new ENVIRONMENT variable for this case, for example "KROKI_EXCALIDRAW_ASSET_PATH" and set default to an empty string?
An empty string behaves actually the same as if the variable were not set so it should work in the default place, when everything is connected to the internet.
But i am not familiar enough with the software to say if it is possible to implement like that...

**Comment by ggrossetie** [comment]
Indeed, we need to load assets used server-side *locally* but on the client side we should load assets from the CDN or provide an option to load them from elsewhere. I don't want to serve these assets from kroki.io.

**Comment by gerlingsm** [comment]
I have opened a pull request.
I have now implemented the change slightly differently via an environment variable, which is empty by default so that the standard behaviour (reloading via CDN) does not change.

**Comment by ggrossetie** [comment]
Fixed in https://github.com/yuzutech/kroki/commit/2965a67b31e98d609d10d4f2ba459dd6eda123c7
Thanks @gerlingsm 🙌🏻
