### ISSUE TITLE
Documentation at docs.kroki.io is out of date

### ISSUE THREAD

**Issue by tbroyer** [yuzutech/kroki#1657]
For example, https://docs.kroki.io/kroki/setup/install/ still mentions the blockdiag companion Docker image.

I suppose this is due to Antora being configured with the `master` branch whereas the branch has been renamed to `main`. Either that and/or deployment is manual and has just not been done since at least 0.22.0.

**Comment by ggrossetie** [comment]
This is not the first time... my guess is that Netlify is using an aggressive cache.

> I suppose this is due to Antora being configured with the master branch whereas the branch has been renamed to main.

We are using the `main` branch: 
https://github.com/yuzutech/docs.kroki.io/blob/16098d29615380ae1fc2ea31ff886189f8554c38/site.yml#L8-L11

Where did you see the `master` branch reference?

> Either that and/or deployment is manual and has just not been done since at least 0.22.0.

Last publish was 9 days ago: https://github.com/yuzutech/docs.kroki.io/actions/runs/6381844024

**Comment by ggrossetie** [comment]
Fixed in https://github.com/yuzutech/docs.kroki.io/commit/592c810bdb25ca8007ce94ba5d9244666491872a

**Comment by ggrossetie** [comment]
Thanks for the heads-up! 🤗

**Comment by tbroyer** [comment]
> Where did you see the `master` branch reference?

In https://github.com/yuzutech/kroki/blob/d7e4dcd25100ee33159f6780a98b0bd213bfa01a/docs/antora.yml#L3 (but I have to admit I know practically nothing about Antora so it might have nothing to do with the actual Git branch and only the version name that appears on the website)

**Comment by ggrossetie** [comment]
> (but I have to admit I know practically nothing about Antora so it might have nothing to do with the actual Git branch and only the version name that appears on the website)

`master` was used in Antora 2.x to indicate an unversioned component: https://docs.antora.org/antora/3.0/whats-new/#new-unversioned-component-version-value

Since it's deprecated in Antora 3.0 (and it will probably be removed in Antora 4.x.), I will use the new value `~` (null) to avoid confusion.
