### ISSUE TITLE
(Unified) Text output format and PlantUML 

### ISSUE THREAD

**Issue by llaville** [yuzutech/kroki#168]
Hello Guillaume,

First, as it is my first report, I would like to thank you for this best unified API solution. It's very plaisant to play with it.

Second, as i work now on plantuml class diagram, i've found that there are multiple output formats, but i don't see any references in the documentation. Did i missed something (a specific page) ?

BTW, great 400 page on online demo server : 

![kroki_io_400](https://user-images.githubusercontent.com/364342/79848579-8e723e80-83c1-11ea-834e-9fc1caf144f7.png)

When I see this, I've tried the `txt` format that we should avoid with UTF-8 char, and used instead `utxt`

Example with my statements 

```
@startuml
namespace Bartlett.GraphUml {
  class ClassDiagramBuilder << class >> {
    +{static} OPTIONS_DEFAULTS : array = […] {readOnly}

    –graph : Graph
    –options : array
    –formatterFactory : FormatterFactory
    --
    +__construct(graph : Graphp.Graph.Graph, options : array = )
    +createVertexClass(class : mixed) : Graphp.Graph.Vertex
    +createVertexExtension(extension : mixed) : Graphp.Graph.Vertex
    –getInterfaces(reflection : ReflectionClass) : array

  }
  interface ClassDiagramBuilderInterface << interface >> {
    +{static} OPTIONS_DEFAULTS : array = […] {readOnly}

    --
    +{abstract}createVertexClass(class) : Graphp.Graph.Vertex
    +{abstract}createVertexExtension(extension) : Graphp.Graph.Vertex

  }
}
Bartlett.GraphUml.ClassDiagramBuilder ..|> Bartlett.GraphUml.ClassDiagramBuilderInterface
@enduml
```

That give with `txt` format such result 
```
,---------------------------------------------------------------.
|ClassDiagramBuilder                                            |
|---------------------------------------------------------------|
|+OPTIONS_DEFAULTS : array = [â€¦] {readOnly}                     |
|                                                               |
|-graph : Graph                                                 |
|-options : array                                               |
|-formatterFactory : FormatterFactory                           |
|--                                                             |
|---------------------------------------------------------------|
|+__construct(graph : Graphp.Graph.Graph, options : array = )   |
|+createVertexClass(class : mixed) : Graphp.Graph.Vertex        |
|+createVertexExtension(extension : mixed) : Graphp.Graph.Vertex|
|-getInterfaces(reflection : ReflectionClass) : array           |
`---------------------------------------------------------------'
                                |                                
                                |                                
    ,-------------------------------------------------------.    
    |ClassDiagramBuilderInterface                           |    
    |-------------------------------------------------------|    
    |+OPTIONS_DEFAULTS : array = [â€¦] {readOnly}             |    
    |                                                       |    
    |--                                                     |    
    |-------------------------------------------------------|    
    |+createVertexClass(class) : Graphp.Graph.Vertex        |    
    |+createVertexExtension(extension) : Graphp.Graph.Vertex|    
    `-------------------------------------------------------'    
```

And then with `utxt` format
```
,---------------------------------------------------------------.
|ClassDiagramBuilder                                            |
|---------------------------------------------------------------|
|+OPTIONS_DEFAULTS : array = […] {readOnly}                     |
|                                                               |
|-graph : Graph                                                 |
|-options : array                                               |
|-formatterFactory : FormatterFactory                           |
|--                                                             |
|---------------------------------------------------------------|
|+__construct(graph : Graphp.Graph.Graph, options : array = )   |
|+createVertexClass(class : mixed) : Graphp.Graph.Vertex        |
|+createVertexExtension(extension : mixed) : Graphp.Graph.Vertex|
|-getInterfaces(reflection : ReflectionClass) : array           |
`---------------------------------------------------------------'
                                |                                
                                |                                
    ,-------------------------------------------------------.    
    |ClassDiagramBuilderInterface                           |    
    |-------------------------------------------------------|    
    |+OPTIONS_DEFAULTS : array = […] {readOnly}             |    
    |                                                       |    
    |--                                                     |    
    |-------------------------------------------------------|    
    |+createVertexClass(class) : Graphp.Graph.Vertex        |    
    |+createVertexExtension(extension) : Graphp.Graph.Vertex|    
    `-------------------------------------------------------'    
```

It's almost good for me, except that the namespace (package) is missing (see png format below), and the arrow of implemention edge is missing too

![kroki_io_plantuml](https://user-images.githubusercontent.com/364342/79849187-6e8f4a80-83c2-11ea-8519-3c0b072c54de.png)

Thanks again
Laurent

**Comment by Mogztter** [comment]
Hello @llaville and thanks for your kind words :blush: 

> Second, as i work now on plantuml class diagram, i've found that there are multiple output formats, but i don't see any references in the documentation. Did i missed something (a specific page) ?

For now, we only have this table but the `utxt` and `txt` are missing: https://kroki.io/#support
Having said that, I think we should create a new page in the documentation: https://docs.kroki.io.
If you want to do it, I will gladly merge your contribution. To do that, you should create new file in here: https://github.com/yuzutech/kroki/tree/master/docs/modules/ROOT/pages. The documentation is written in AsciiDoc, generated by Antora and published on Netlify.

> It's almost good for me, except that the namespace (package) is missing (see png format below), and the arrow of implemention edge is missing too

Kroki provides an unified API on top of PlantUML, so you should open an issue upstream: https://github.com/plantuml/plantuml
as I get the same result using PlantUML directly:

http://www.plantuml.com/plantuml/txt/hL9TJi9047xlAUQnHEa12194m90OCGA-64F6xO1DjZ-PJXD8RS8Tl8C7uoGkNTi4AT477zZGsUzdvfljfu8iMQYT24DA4rG40rFH9EBTCYPlYr13xW0eZMaADuTp6E2QCHnaWVQ9eTlzlkprIYJ0HMva9L05J1_ca-dzR3aSZQyNT_CPT02PSGjNyBpVVRv0peJ-DDBRmYcf-zt7-c1hWALzLOmJ2U8ehVXLUHLpY2B4OrGIyzRSZuzB5jfksyQMIsLKX3Cbxf5FOgUrvoNKTdMxBIkWc53eYLXeKuRXsjax40ORybi_zIpob3lQ24MfyN2f-lUxXes7P189yGeLfIxJIfCIIt-iFyhMMdLQXbkONr3nclPOYnuMMYF_PQbL-Zc-cknHIN4cnlEZDxERWpoZObCed9FtxJMzQizxxy6Ve7LmJfyYFmlr5m00

**Comment by llaville** [comment]
Thanks for your quick answer.
I'll open an issue on plantuml project tomorrow.
For contribution, its possible. I'll see how to do tomorrow or in 2 days.

**Comment by Mogztter** [comment]
Perfect!
@llaville Can we close this issue?

**Comment by llaville** [comment]
@Mogztter yes will do, as it is not related to Kroki. Thanks !
