### ISSUE TITLE
Structurizr: How to generate keys / legends?

### ISSUE THREAD

**Issue by cc-stjm** [yuzutech/kroki#1686]
Is there a way to generate the keys / legends associated with a Structurizr view?

It seems that if you're using the Structurizr CLI to export the plantUML views, the legends are generated as separate files, as e.g. `structurizr-systemContext-key.puml` for the key for the systemContext view.

However, providing systemContext-key to Kroki doesn't generate the legend.

**Comment by 0xCtor** [comment]
Did you find the answer to this? I haven't been able to find a way to generate diagram legends.

**Comment by simonbrowndotje** [comment]
If supported by the exporter, you just need to output it; see https://github.com/structurizr/cli/blob/master/src/main/java/com/structurizr/cli/export/ExportCommand.java#L148 for an example.

**Comment by ggrossetie** [comment]
Kroki outputs a single image, is it possible to embed/include the legend definition in the diagram (and then convert it to an image)?

Something like:
```java
plantumlCommand.convert(diagram.getDefinition() + "\\n\\n" + diagram.getLegend().getDefinition(), fileFormat, new JsonObject());
```
