### ISSUE TITLE
Update Java version to 17 or 21

### ISSUE THREAD

**Issue by heyLu** [yuzutech/kroki#1688]
Hi, would an update of kroki's Java version to 17 or 21 be welcome?

The company I work at uses kroki internally and has a policy for only allowing the last two LTS versions in production and would thus like to update to Java 17 or later.

If it's welcome, I'd open a PR to do the update.

**Comment by ggrossetie** [comment]
Hey @heyLu 

Yes, I'm willing to upgrade to Java 17. You can submit a PR 👍🏻

**Comment by ggrossetie** [comment]
We can keep it open until the minimum version is Java 17?
