### ISSUE TITLE
Mermaid Converting Not Working

### ISSUE THREAD

**Issue by Partyschnitzel** [yuzutech/kroki#1690]
Hello!
The conversion of Mermaid diagrams is currently not working with the Kroki service. Not even in the example on the Kroki webpage itself.

**Comment by ggrossetie** [comment]
Hey!

I've just restarted the service, it should be up now.
In the future, please use the community chat at [kroki.zulipchat.com](https://kroki.zulipchat.com/) to report issues with the public instance. The issue tracker is for reporting bugs and feature proposals. Thanks!
