### ISSUE TITLE
#Try - Mermaid Error 400

### ISSUE THREAD

**Issue by MKE-Lorch** [yuzutech/kroki#1696]
In my asciidoctor-kroki project my mermaid diagrams are not rendered anymore. I've checked on https://kroki.io/#try an for me even the basic marmaid example is not working anymore. The error message is the same. Other diagrams are working properly with asciidoctor-kroki and on https://kroki.io/#try.

![image](https://github.com/yuzutech/kroki/assets/81557967/b90b1d48-9d9d-4fa2-9f65-145c4f30dda9)

**Comment by jmooring** [comment]
Problem seems limited to mermaid. This fails as well:

```text
sequenceDiagram
  participant Alice
  participant Bob
  Alice->John: Hello John, how are you?
  loop Healthcheck
    John->John: Fight against hypochondria
  end
  Note right of John: Rational thoughts prevail...
  John-->Alice: Great!
  John->Bob: How about you?
  Bob-->John: Jolly good!
```

**Comment by ggrossetie** [comment]
Hey!

It's a known issue. Mermaid has stability issues (Chrome GPU process regularly crashes).
Please use the community chat at [kroki.zulipchat.com](https://kroki.zulipchat.com/) to report issues with the public instance. The issue tracker is for reporting bugs and feature proposals.
