### ISSUE TITLE
Support for choosing the layout engine for D2 in GitLab code blocks

### ISSUE THREAD

**Issue by mak-dunkelziffer** [yuzutech/kroki#1699]
I'm not sure, whether this has to be solved on the side of Kroki or GitLab.

Currently, whenever you create a D2 code block in GitLab, it uses D2's default layout engine "Dagre". Most of the time, the layout engine "ELK" produces nicer results and it also supports a slightly different feature set. It would be nice to have support for that. 

I guess GitLab code blocks don't support params. Correct me if I'm wrong. To my knowledge the following isn't possible:
`````
```d2(layout="elk")
# my diagram
```
`````

So if we can't have real params for code blocks, the next best thing is to create a new code block that uses the other layout engines under the hood. E.g.
`````
```d2elk
# my diagram
```
`````
or
`````
```d2tala
# my diagram
```
`````

This isn't very elegant and extra work for you, but luckily the number of layout engines is finite and not growing that quickly. Would you consider this an acceptable solution?

**Comment by ggrossetie** [comment]
This is an integration issue with GitLab/Markdown. Kroki already supports it (see below).

You will need to open an issue at https://gitlab.com/gitlab-org/gitlab/-/issues to support sending diagram options to the Kroki server. Regarding which Markdown syntax we should use, I don't have a strong opinion. AsciiDoc has built-in support for attributes:

```
[d2,layout=elk]
....
# my diagram
....
```

Please note that TALA is a proprietary engine and is not included in Kroki. It might be possible to add it by extending the base image.

#### Default layout (diagre)

<img src="https://kroki.io/d2/svg/eNqlUj1vgzAQ3f0r7g-EpZuHSlW7MLRFSpgrC07BwsGWfTRCEf-9Z2MimlYZ2gF0H37P7-7Z2GOQcBEAoVMOJTh1xJjRZLA4jYa0M1wmP6KYxRjQS6j5D5cVgD7YYRYD0tn6XsLbEiRSsucIeEZj4BDjVGV6RVzShPnyVFv4AlmP7UerSK2N37TExixuyGD3yF01hJMmQv_v7vd85s9522AIlod6YYVQrfk6GKvnDUrYL8HtdM1k9NBm-ruj5fusJ2UkvA-MQ6hSmknrUuQdpDUXG7VxmI1U11kGG_aaPWTzPqMpT1UJ-xSL5GvEZBOL7Nur6hEaZczqbnEljacXpj_3spJYSdLupstD04G2sCt7WktRlxJaHZxR04-JNkdUE6Usjz7tP5C3Pe5aFToJD7yiL8hLBuk=" height=300/>

```
https://kroki.io/d2/svg/eNqlUj1vgzAQ3f0r7g-EpZuHSlW7MLRFSpgrC07BwsGWfTRCEf-9Z2MimlYZ2gF0H37P7-7Z2GOQcBEAoVMOJTh1xJjRZLA4jYa0M1wmP6KYxRjQS6j5D5cVgD7YYRYD0tn6XsLbEiRSsucIeEZj4BDjVGV6RVzShPnyVFv4AlmP7UerSK2N37TExixuyGD3yF01hJMmQv_v7vd85s9522AIlod6YYVQrfk6GKvnDUrYL8HtdM1k9NBm-ruj5fusJ2UkvA-MQ6hSmknrUuQdpDUXG7VxmI1U11kGG_aaPWTzPqMpT1UJ-xSL5GvEZBOL7Nur6hEaZczqbnEljacXpj_3spJYSdLupstD04G2sCt7WktRlxJaHZxR04-JNkdUE6Usjz7tP5C3Pe5aFToJD7yiL8hLBuk=
```

#### ELK layout

<img src="https://kroki.io/d2/svg/eNqlUj1vgzAQ3f0r7g-EpZuHSlW7MLRFSpgrC07BwsGWfTRCEf-9Z2MimlYZ2gF0H37P7-7Z2GOQcBEAoVMOJTh1xJjRZLA4jYa0M1wmP6KYxRjQS6j5D5cVgD7YYRYD0tn6XsLbEiRSsucIeEZj4BDjVGV6RVzShPnyVFv4AlmP7UerSK2N37TExixuyGD3yF01hJMmQv_v7vd85s9522AIlod6YYVQrfk6GKvnDUrYL8HtdM1k9NBm-ruj5fusJ2UkvA-MQ6hSmknrUuQdpDUXG7VxmI1U11kGG_aaPWTzPqMpT1UJ-xSL5GvEZBOL7Nur6hEaZczqbnEljacXpj_3spJYSdLupstD04G2sCt7WktRlxJaHZxR04-JNkdUE6Usjz7tP5C3Pe5aFToJD7yiL8hLBuk=?layout=elk" height=300/>

```
https://kroki.io/d2/svg/eNqlUj1vgzAQ3f0r7g-EpZuHSlW7MLRFSpgrC07BwsGWfTRCEf-9Z2MimlYZ2gF0H37P7-7Z2GOQcBEAoVMOJTh1xJjRZLA4jYa0M1wmP6KYxRjQS6j5D5cVgD7YYRYD0tn6XsLbEiRSsucIeEZj4BDjVGV6RVzShPnyVFv4AlmP7UerSK2N37TExixuyGD3yF01hJMmQv_v7vd85s9522AIlod6YYVQrfk6GKvnDUrYL8HtdM1k9NBm-ruj5fusJ2UkvA-MQ6hSmknrUuQdpDUXG7VxmI1U11kGG_aaPWTzPqMpT1UJ-xSL5GvEZBOL7Nur6hEaZczqbnEljacXpj_3spJYSdLupstD04G2sCt7WktRlxJaHZxR04-JNkdUE6Usjz7tP5C3Pe5aFToJD7yiL8hLBuk=?layout=elk
```

**Comment by mak-dunkelziffer** [comment]
Thank's for the fast reply. Good to know that AsciiDoc supports this out of the box. I guess the chances to make a syntax change happen in Markdown are pretty slim. Instead, I opened an issue for D2 itself to make it possible to set those params within the diagram itself.

**Comment by ggrossetie** [comment]
Using `d2elk` or `d2tala` could work but the integration will need to translate it to `d2` using `elk` or `tala` layout engine.
It also does not scale very well if you want to add another option (i.e., `d2talanoborder` 😬)

I think it's a good idea to set those parameters within the diagram itself.

**Comment by mak-dunkelziffer** [comment]
I actually tried `d2elk` and `d2-elk` and hoped that Kroki would just support one of those. But this approach really isn't feasible. D2 has too many CLI options. It has a `theme` option with ~20 options, a boolean `sketch` option, 3 layout engines. You simply can't support all possible combinations.

Also, having to specify the layout engine on the CLI is actually REALLY cumbersome, because the layout engines support slightly different features. Thus, your diagrams are not self-contained anymore, because they might use a feature, that only one layout engine understands and you need to guess that engine when compiling the diagram.
