### ISSUE TITLE
Relative link Issue : relative to site base instead of kroki server

### ISSUE THREAD

**Issue by ezzle** [yuzutech/kroki#1703]
Sample diagrams 

https://stackblitz.com/edit/vite-65uaqt?file=docs%2Findex.md

Tshitshi Kia Ntoni
[2:24 PM](https://kroki.zulipchat.com/#narrow/stream/232085-users/topic/Relative.20link.3A.20relative.20to.20site.20base.20instead.20of.20kroki.20server/near/418635918)
Hello.

I am using Kroki with plantuml to render diagrams in a vitepress generated site.

Unfortunately, relative links in a kroki plantuml diagrams are resolved relative to the kroki server instead of my own web site base site url
"graph/slot/--direct-type/page" relative url generates "https://kroki.io/plantuml/svg/graph/slot/--direct-type/page" instead of "https://mybase/graph/slot/--direct-type/page".

How can I get the desired behavior?

Thanks in advance.

Best regards

Tshitshi

**Comment by ggrossetie** [comment]
Please do not cross post, we are already discussing this issue on Zulip.
