### ISSUE TITLE
New release planned ?

### ISSUE THREAD

**Issue by xavier-calland** [yuzutech/kroki#1728]
I wonder if a new version is planned.
It would be nice to have more recent Docker images (in my case it's mainly to have Mermaid in the latest version).

**Comment by madmas** [comment]
@xavier-calland I assume you refer to the fact that the latest image 0.24.1 is using 10.6.1 of mermaid, not the latest version, 10.9.0, right?

I would also welcome a new release :)

**Comment by xavier-calland** [comment]
> @xavier-calland I assume you refer to the fact that the latest image 0.24.1 is using 10.6.1 of mermaid, not the latest version, 10.9.0, right?

Exactly

**Comment by ggrossetie** [comment]
Yes, I will probably release a new version at the end of the week. Please use the community chat to discuss new release/roadmap: https://kroki.zulipchat.com/

Thanks!
