### ISSUE TITLE
Bug: Mermaid flowchart option `defaultRenderer` not configurable

### ISSUE THREAD

**Issue by butterlyn** [yuzutech/kroki#1732]
Error results from trying to set the mermaid flowchart option `defaultRenderer`.

For example, the below mermaid flowchart will render on the mermaid website, but throw an error with kroki:

```kroki-mermaid
---
config:
  flowchart:
    defaultRenderer: "elk"
---
flowchart TD
    A[Start] --> B{Is it?}
    B -->|Yes| C[OK]
    C --> D[Rethink]
    D --> B
    B ---->|No| E[End]
```

**Comment by ggrossetie** [comment]
It seems to be working fine on kroki.io

https://kroki.io/mermaid/svg/eNo9i7EKwjAURfd8xaP7-4EOim06iKBQXSRkKM2LDQ0JpBEH47_bpNDxnnsOIrLRO21eNQPQ1n_GaQgxDwBFenjb2JNTFCjUUJGdK4Zrs5vw4MU9iXtcpwTEAzTf8wImHn_lajJLT1oStOJ2kQW2ReSipzgZN2-Qb_Ve5e7qE3Sic0qyP_SML1k=

**Comment by butterlyn** [comment]
Issue seems to have been resolved in the last release.

**Comment by butterlyn** [comment]
Issue seems to have been resolved in the last release.
