### ISSUE TITLE
Increase body limit when rendering diagrams

### ISSUE THREAD

**Issue by eryalito** [yuzutech/kroki#1760]
Hey!

I found this https://github.com/yuzutech/kroki/issues/1332 when rendering a small but full of images excalidraw diagram. I didn't found a way of changing this limit without some code changes. Seems that the tweak on this would be minimal, maintaining backwards compatibility by just changing the line 

https://github.com/yuzutech/kroki/blob/5023863bfd81f58d46b9947e8b354d97b5352370/excalidraw/src/index.js#L14

to something like

```js
const diagramSource = await micro.text(req, { limit: (process.env.MAX_BODY_SIZE ?? '1mb'), encoding: 'utf8' })
```

I think a similar approach would be fine in other tools:
https://github.com/yuzutech/kroki/blob/main/diagrams.net/src/index.js#L22
https://github.com/yuzutech/kroki/blob/main/mermaid/src/index.js#L30
...

Would you accept a PR including these changes?

**Comment by ggrossetie** [comment]
Yes sure, the environment variable must be prefixed by `KROKI_` but apart from that 👍🏻

**Comment by ggrossetie** [comment]
Fixed in https://github.com/yuzutech/kroki/commit/21c486c4df824ef7d2c0f7bdd14c63e82b6ce29f
