### ISSUE TITLE
Mermaid charts are loading irregularly in the public API

### ISSUE THREAD

**Issue by scali** [yuzutech/kroki#1783]
Quite same as #1443, but a bit different

Going to kroki.io and to samples of Mermaid chart. Going to the link of the diagrams directly (Sequence Diagram or Gantt) :  

For example, this link : 
https://kroki.io/mermaid/svg/eNpljzFuwzAMRXefgtlrZzcKBymCtMjQoTegZdYiwoqqTLfw7SMrSDKEi4j_H6nPaqLfmYKjA-OY8KeCXBGTseOIwWAv7OhJfdO-aMWtu5P60MIHiSis_Qt4_QdMBIvOu0KKaswEinnnyZ2LuNbK3zYcefQGOCKHycAvUZ3XMCTGglMYyvupRpAKq99wHf1CYw0oYF7n7Ezw2qdtFxP9IUvTNNX9s7orsVt4T4S2eRhdPiufsUbvdbZH-KzXt4wnFVlgVB021QUIImOl

took from the [offical page of exemples of kroki.io](https://kroki.io/examples.html#mermaid-seqdiag)

The link loads irregularly, and when it failed, there is this message :  

> Convert plain text diagrams to images !
> 🤖 bip... bip... something wrong happened!
> 400 Error: An error occurred while converting the diagram 

I'm using kroki to load images in a asciidoctor/antora document and have the same kind of error : 
![Error 400: An error occurred while converting the diagram](https://github.com/user-attachments/assets/20e84704-f5bc-48fb-b37f-35bca6d2ebb8)

**Comment by bartkl** [comment]
I'm getting this exact issue. Just got to know about Kroki! and the AsciiDoctor extension and was going mad about not understanding how unpredictable the extension seemed. Turns out (as op points out) it's the Kroki Mermaid endpoint.

FYI: With GraphViz it's working consistently.

**Comment by scali** [comment]
As I have this option, I've ended up by deploying a self managed version of Kroki, as described [here](https://docs.kroki.io/kroki/setup/use-kubernetes/), and setting the `kroki-server-url` parameter in the playbook configuration file (`antora-playbook.yml`)

```yml
asciidoc:
  extensions:
  - asciidoctor-kroki
  attributes:
    kroki-fetch-diagram: false
    kroki-server-url: https://kroki.my-company.domain
```

The service run nicely and the charts are loading now. 

Maybe the public site of kroki.io is sometime overloaded.

**Comment by jamesward** [comment]
I'm now getting this error consistently. Can we get an update on ETA to fix?

**Comment by ggrossetie** [comment]
Should be fixed now.

**Comment by Brianwind** [comment]
getting the same problem now, even the example in the website failed.
![image](https://github.com/user-attachments/assets/52a6707f-7dcb-49f2-9776-913c8befc97c)
check this url:
https://kroki.io/mermaid/svg/eNpNzr0OgjAcBPCdp7hRB-QNNHz4Masb6VBK0zZg_6S2GhTf3cJgnH93l1OODxrXKgHyGrkdyUowpOl2KrmFlv2ACcUKR4InKON1aDaCbtkYXsFLobPOUWewjgvF3EP5xomec1qQ9c40MbbDJ3q5eFXjLAdy3liFJqg72M_2NS6au1lMK_k_HeK99kGCLz2WfAHnUzg5

**Comment by ggrossetie** [comment]
I just deployed a new version that includes https://github.com/yuzutech/kroki/pull/1745. It's not perfect but hopefully it should improve Mermaid's reliability.


Please open a new issue if you are still experiencing issues. If possible, please include the time range during which you observed instabilities. It greatly helps troubleshooting 😄
