### ISSUE TITLE
[Feature Request] Add live editor for kroki.

### ISSUE THREAD

**Issue by cathaysia** [yuzutech/kroki#1815]
There is a live editor on the kroki website. However, there is no such live editor in the self-hosted kroki. Are there plans to add such a feature?

**Comment by ggrossetie** [comment]
Hello! Not really, the "live editor" on the kroki.io website is merely a `<textarea>`  with a bit of JavaScript to encode the text (using the code described in the documentation: https://docs.kroki.io/kroki/setup/encode-diagram/#javascript).

I don't intend to build a full-featured text editor for diagrams so I recommend to use your favorite text editor with a Kroki extension to get a live preview. See: https://docs.kroki.io/kroki/setup/third-party-tools/
