### ISSUE TITLE
Add an API that returns the diagram librairies versions and the server version

### ISSUE THREAD

**Issue by Mogztter** [yuzutech/kroki#297]
Currently, we only have an HTML page https://a.kroki.io but it could be useful to have an endpoint if we want to use that information programmatically.

For instance, we could locally cache images depending on the diagram library version:

```
plantuml-1-2020-10/
  54cae01691d18960adccb024b0e5b01b.png

plantuml-1-2020-15/
  54cae01691d18960adccb024b0e5b01b.png
```

A few ideas:

- `/about`
- `/version`
- `/versions`

Alternatively, we could also use a "status" route to check that the server is alive and we could use this opportunity to return server infos:

- `/status`
- `/_status`

**Comment by llaville** [comment]
About `/status` or `/_status`, I'd like to recommend `/health` (most used in microservices / containers API architecture: see https://microservices.io/patterns/observability/health-check-api.html)

**Comment by Mogztter** [comment]
That's a good suggestion. Do you have any examples of the format of the response?
I don't want to distort the initial purpose of an health API with server informations... that's why I'm curious what kind of information is typically returns.

Maybe we need both an health and an info/version API or maybe not...

**Comment by llaville** [comment]
There are no real standard for health checks, but to minima we should have a json response with a `status` field that identify if service monitoring is **healthy** or **unhealthy** (these values are used in docker architecture)
Other metadata should be considered as optional.

Perharps an article that may help you:  https://tools.ietf.org/id/draft-inadarei-api-health-check-01.html

**Comment by Mogztter** [comment]
Thanks @llaville!
Maybe we can start with something as simple as:

```http
GET /health HTTP/1.1
```
```

Host: kroki.io
Accept: application/health+json

HTTP/1.1 200 OK
Content-Type: application/health+json
```
```json
{
  "status": "pass",
  "version" : {
    "number" : "0.5.0",
    "build_hash" : "f6c3a9f",
    "actdiag_version": "2.0.0",
    "blockdiag_version": "2.0.1",
    "bpmn_version": "6.5.1",
    "bytefield_version": "1.4.3",
    "c4plantuml_version": "1.2020.10",
    "ditaa_version": "1.3.13",
    "erd_version": "0.1.3.0",
    "graphviz_version": "2.40.1",
    "mermaid_version": "8.5.1",
    "nomnoml_version": "0.7.2",
    "nwdiag_version": "2.0.0",
    "packetdiag_version": "2.0.0",
    "plantuml_version": "1.2020.10",
    "rackdiag_version": "2.0.0",
    "seqdiag_version": "2.0.0",
    "svgbob_version": "0.4.2",
    "umlet_version": "14.3.0",
    "vega_version": "5.12.1",
    "vegalite_version": "4.12.2",
    "wavedrom_version": "2.3.2"
  }
}
```

**Comment by llaville** [comment]
+1 but I think you may removes redundant **_version** suffix, because parent is already **version**

Why not such suggestion : 
```
{
  "status": "pass",
  "version" : {
    "number" : "0.5.0",
    "build_hash" : "f6c3a9f",
    "actdiag": "2.0.0",
    "blockdiag": "2.0.1",
    "bpmn": "6.5.1",
    "bytefield": "1.4.3",
    "c4plantuml": "1.2020.10",
    "ditaa": "1.3.13",
    "erd": "0.1.3.0",
    "graphviz": "2.40.1",
    "mermaid": "8.5.1",
    "nomnoml": "0.7.2",
    "nwdiag": "2.0.0",
    "packetdiag": "2.0.0",
    "plantuml": "1.2020.10",
    "rackdiag": "2.0.0",
    "seqdiag": "2.0.0",
    "svgbob": "0.4.2",
    "umlet": "14.3.0",
    "vega": "5.12.1",
    "vegalite": "4.12.2",
    "wavedrom": "2.3.2"
  }
}
```

And even more with kroki core related informations : 
```
{
  "status": "pass",
  "version" : {
    "kroki": {
      "number" : "0.5.0",
      "build_hash" : "f6c3a9f",
    },
    "actdiag": "2.0.0",
    "blockdiag": "2.0.1",
    "bpmn": "6.5.1",
    "bytefield": "1.4.3",
    "c4plantuml": "1.2020.10",
    "ditaa": "1.3.13",
    "erd": "0.1.3.0",
    "graphviz": "2.40.1",
    "mermaid": "8.5.1",
    "nomnoml": "0.7.2",
    "nwdiag": "2.0.0",
    "packetdiag": "2.0.0",
    "plantuml": "1.2020.10",
    "rackdiag": "2.0.0",
    "seqdiag": "2.0.0",
    "svgbob": "0.4.2",
    "umlet": "14.3.0",
    "vega": "5.12.1",
    "vegalite": "4.12.2",
    "wavedrom": "2.3.2"
  }
}
```

**Comment by Mogztter** [comment]
Yes that's a good idea, I took inspirations from Elasticsearch:

```
curl -XGET localhost:9200
```
```json
{
    "name": "node",
    "cluster_name": "elasticsearch-cluster",
    "version": {
        "number": "2.3.4",
        "build_hash": "dcxbgvzdfbbhfxbhx",
        "build_timestamp": "2016-06-30T11:24:31Z",
        "build_snapshot": false,
        "lucene_version": "5.5.0"
    },
    "tagline": "You Know, for Search"
}
```

But your last proposal is quite nice 👍

**Comment by llaville** [comment]
glad you like it !
