### ISSUE TITLE
Kroki server 7.1 could not be run with java -jar

### ISSUE THREAD

**Issue by Rizzen59** [yuzutech/kroki#350]
Hi,

First, thanks for you work. 

I'm trying to start the version 0.7.1 with java -jar command but it's not possible (no attribute maniphest ....)

When i compare with version 0.6.0, there are size and the number of file which is different. So may be a compilation failed ?

**Comment by Mogztter** [comment]
Hi @Rizzen59 

> First, thanks for you work.

Greatly appreciated :smile: 

> I'm trying to start the version 0.7.1 with java -jar command but it's not possible (no attribute maniphest ....)
> When i compare with version 0.6.0, there are size and the number of file which is different. So may be a compilation failed ?

Sorry about that, I uploaded the wrong jar file that only contains the server code.
I will upload the correct jar file as soon as possible.

**Comment by Mogztter** [comment]
It should be OK now:

![updated](https://user-images.githubusercontent.com/333276/91036992-914b9d00-e608-11ea-9d0e-7b69234c3e02.png)
