### ISSUE TITLE
How to set font

### ISSUE THREAD

**Issue by mhf-ir** [yuzutech/kroki#46]
How to set font in rendered svg ?

**Comment by Mogztter** [comment]
Hello Muhammad, could you please be more specific? Are you using a local instance? Which diagram library are you using?

**Comment by mhf-ir** [comment]
Using website rest https://kroki.io/

**Comment by Mogztter** [comment]
If you are using PlantUML and svg, you can use `skinparam defaultFontName Roboto`. In the following example I'm using the font "Roboto mono":

![roboto-mono](https://user-images.githubusercontent.com/333276/72502407-81313b00-3839-11ea-84db-a50b86c8248b.png)

The font should be installed on your system.
The hosted service only contains system fonts so it won't work if you export the diagram as png or jpeg.
