### ISSUE TITLE
Add C4 Plantuml Deployment Diagram support

### ISSUE THREAD

**Issue by matesitox** [yuzutech/kroki#47]
Upstream C4 Plantuml [now supports](https://github.com/kirchsth/C4-PlantUML/blob/master/C4_Deployment.puml) the [C4 Deployment diagram](https://c4model.com/#DeploymentDiagram). Would it be possible to add support for this to kroki by default?

**Comment by Mogztter** [comment]
Sure, as soon as it's effectively available in upstream: https://github.com/RicardoNiepel/C4-PlantUML
For now, it's only available in a pull request: https://github.com/RicardoNiepel/C4-PlantUML/pull/34

**Comment by matesitox** [comment]
Awesome, I'll see if I can help out upstream getting it through. Thanks!

**Comment by Mogztter** [comment]
@matesitox Good news, C4 Deployment diagram is now merged and available in a release! https://github.com/plantuml-stdlib/C4-PlantUML/blob/v2.0.0/C4_Deployment.puml

**Comment by matesitox** [comment]
🙂
