### ISSUE TITLE
Support for plantuml include directive on self hosted servers

### ISSUE THREAD

**Issue by AXGKl** [yuzutech/kroki#49]
### About
plantuml's `include` directive is a powerful feature, as illustrated e.g. with [C4](https://github.com/RicardoNiepel/C4-PlantUML) but also in corporate scenarios, allowing to switch diagrams into a common CI, with a single line.

As discussed [here](https://github.com/yuzutech/kroki/issues/33), I think it would be safe to enable (restricted) support for `!include` in self hosted scenarios.

#### include_url
According to [here](http://wiki.plantuml.net/site/preprocessing#including_files) `!include` is also covering the features of `!include_url` meanwhile. We discuss remote and local includes below: 

#### include
In order to safeguard uneducated operators of a self hosted kroki server from unauthorized file reads and cross site attacks  `!include` should  
- only act on a **single preconfigured directory** (e.g. `$PLANTHOME`), if set - and
- accept as parameter **only plain filenames**, without paths.

With those restrictions, I suggest to allow even the configuration of *remote* base urls as `$PLANTHOME` (use case example: Fileservers, with a set of themes).

When there is no such base directory configured, kroki should keep ignoring `!include` lines in diagram bodies (behaviour like now).

#### includesub
This is an `include` variant with the syntax: `!includesub file1.puml!BASIC` where "BASIC" would be only a part of an external definition file.  
I suggest to support it, with the same restrictions as for `!include`.

### Configuration
We are in container age, so I suggest to support as one and only way to configure the presence and location of such a base directory an exported environment variable.

**Comment by Mogztter** [comment]
I'm currently working on https://github.com/yuzutech/kroki/issues/54 and Vega can load data from an URL: https://vega.github.io/vega/docs/data/

I think we should probably use an environment variable to prevent Kroki from attempting to read files from the file system or from the network.
Here's a proposal:

`KROKI_SAFE_MODE`:

- `UNSAFE`: disables any security features.
- `SERVER`: prevents access to files which reside outside of base directory.
- `SECURE`: prevents attempts to read files from the file system or from the network.

A few examples:

**Provided**
```
!include file1.puml
!include /path/to/dir/file2.puml
!include ../file3.puml
!include https://server/file4.puml
!include /file5.puml
!include /path/to/somedir/file6.puml
```

`KROKI_SAFE_MODE` | `PLANTUML_BASE_DIR` | Resolved
------------ | ------------- | ----------------
`UNSAFE` | `/path/to/dir` | <pre>!include /path/to/dir/file1.puml<br>!include /path/to/dir/file2.puml<br>!include /path/to/file3.puml<br>!include https://server/file4.puml<br>!include /file5.puml<br>!include /path/to/somedir/file6.puml</pre>
`UNSAFE` | `https://server/assets` | <pre>!include https://server/assets/file1.puml<br>!include /path/to/dir/file2.puml<br>!include https://server/file3.puml<br>!include https://server/file4.puml<br>!include /file5.puml<br>!include /path/to/somedir/file6.puml</pre>
`SERVER` | `/path/to/dir` | <pre>!include /path/to/dir/file1.puml<br>!include /path/to/dir/file2.puml</pre>
`SERVER` | `https://server` | <pre>!include https://server/file1.puml<br>!include https://server/file4.puml</pre>
`SECURE` | `/path/to/dir` | <pre></pre>

**Comment by Mogztter** [comment]
I wonder if we should be more explicit about the naming: `PLANTUML_INCLUDE_BASE_DIR` and `VEGA_DATA_BASE_DIR`?

**Comment by Mogztter** [comment]
As far as I understand, PlantUML and Vega does not implement a mechanism to prevents access to files which reside outside of a base directory.

So I think we should first implement the following two security modes:

`KROKI_SAFE_MODE`:

- `UNSAFE`: disables any security features.
- `SECURE`: prevents attempts to read files from the file system or from the network.

And then either ask upstream to implement the "base directory" security mechanism or implement it here. 

What do you think @AXGKl?
