### ISSUE TITLE
Feature request: Add support for Pikchr

### ISSUE THREAD

**Issue by arthurbarr** [yuzutech/kroki#515]
Could you please consider adding support for [Pikchr](https://pikchr.org)?

**Comment by Mogztter** [comment]
Hey @arthurbarr 
I actually did consider Pikchr but I couldn't find a pre-built binary. It was also unclear how to get the sources of this project: https://pikchr.org/home/dir?ci=tip :thinking: 

Any idea?

**Comment by arthurbarr** [comment]
It appears to be using Fossil for source code management.  You can get the source doing something like this:

```
fossil clone https://pikchr.org pikchr
fossil open ./pikchr
```

I don't think there's a pre-built version, as it's just a single C file, with a single function as the entrypoint.  So integrating would appear to mean pulling down the latest C file, and then invoking the C function from kroki.

**Comment by arthurbarr** [comment]
Additional docs on [building Pikchr from source](https://pikchr.org/home/doc/trunk/doc/build.md) and [how to integrate Pikchr into new systems](https://pikchr.org/home/doc/trunk/doc/integrate.md)

**Comment by marcusatiliusregulus** [comment]
@arthurbarr i found that fossil complains with your approach of opening the repo. its easier to just create a new folder for the checkout:
```bash
fossil clone https://pikchr.org pikchr
mkdir pikchr-checkout
cd pikchr-checkout
fossil open ../pikchr
```

but there's actually no need to use fossil at all:
just get the preprocessed c file from https://pikchr.org/home/file/pikchr.c
and compile as the Makefile says:
`gcc -O0 -g -Wall -Wextra -DPIKCHR_SHELL pikchr.c -o pikchr -lm`

**Comment by Mogztter** [comment]
For reference, Pikchr now has an official GitHub mirror: https://github.com/drhsqlite/pikchr

> but there's actually no need to use fossil at all:
just get the preprocessed c file from pikchr.org/home/file/pikchr.c
and compile as the Makefile says:
gcc -O0 -g -Wall -Wextra -DPIKCHR_SHELL pikchr.c -o pikchr -lm

I can confirm that the following is working fine, thanks :+1: 

Now the only blocker is that the CLI does not seem to read diagram from stdin (and I don't want to write temporary files on the disk). I never wrote C code but I will see what I can do...

If someone is familiar with C and/or knows how to implement this feature please come forward! The entry point seems to be: https://github.com/drhsqlite/pikchr/blob/91f0247783fc7ae7941f3ec5dd9747518c345b91/pikchr.c#L7716

**Comment by Mogztter** [comment]
Gave it a try: https://github.com/drhsqlite/pikchr/pull/1
