### ISSUE TITLE
Feature request: add syntrax support

### ISSUE THREAD

**Issue by lorrden** [yuzutech/kroki#517]
Syntrax is a tool for generating syntax diagrams, is is available here:

https://kevinpt.github.io/syntrax/

It would be great if this could be supported as well.

**Comment by Mogztter** [comment]
I considered this diagram library but as far as I know it's a Python DSL.
As a result, it can execute arbitrary Python code, it's really unsafe to execute untrusted Syntrax definitions.

**Comment by Mogztter** [comment]
I'm closing this issue since we already have another issue to support Railroad diagrams: https://github.com/yuzutech/kroki/issues/6

Feel free to add a comment about Syntrax.
