### ISSUE TITLE
Sample from C4-PlantUML does not render (Function not found)

### ISSUE THREAD

**Issue by kjeremy** [yuzutech/kroki#549]
I've embedded the following sample into a markdown file https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/samples/C4_Container%20Diagram%20Sample%20-%20bigbankplc-icons.puml and kroki will not render. It complains that `Function not found Container (line: 275)" as in:

```c4plantuml
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
' uncomment the following line and comment the first to use locally
' !include C4_Container.puml
!include DEVICONS/angular.puml
!include DEVICONS/dotnet.puml
!include DEVICONS/java.puml
!include DEVICONS/msql_server.puml
!include FONTAWESOME/server.puml
!include FONTAWESOME/envelope.puml

' LAYOUT_TOP_DOWN()
' LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

title Container diagram for Internet Banking System

Person(customer, Customer, "A customer of the bank, with personal bank accounts")

System_Boundary(c1, "Internet Banking") {
    Container(web_app, "Web Application", "Java, Spring MVC", "Delivers the static content and the Internet banking SPA", "java")
    Container(spa, "Single-Page App", "JavaScript, Angular", "Provides all the Internet banking functionality to cutomers via their web browser", "angular")
    Container(mobile_app, "Mobile App", "C#, Xamarin", "Provides a limited subset of the Internet banking functionality to customers via their mobile device", "dotnet")
    ContainerDb(database, "Database", "SQL Database", "Stores user registraion information, hased auth credentials, access logs, etc.", "msql_server")
    Container(backend_api, "API Application", "Java, Docker Container", "Provides Internet banking functionality via API", "server")
}

System_Ext(email_system, "E-Mail System", "The internal Microsoft Exchange system", "envelope")
System_Ext(banking_system, "Mainframe Banking System", "Stores all of the core banking information about customers, accounts, transactions, etc.")

Rel(customer, web_app, "Uses", "HTTPS")
Rel(customer, spa, "Uses", "HTTPS")
Rel(customer, mobile_app, "Uses")

Rel_Neighbor(web_app, spa, "Delivers")
Rel(spa, backend_api, "Uses", "async, JSON/HTTPS")
Rel(mobile_app, backend_api, "Uses", "async, JSON/HTTPS")
Rel_Back_Neighbor(database, backend_api, "Reads from and writes to", "sync, JDBC")

Rel_Back(customer, email_system, "Sends e-mails to")
Rel_Back(email_system, backend_api, "Sends e-mails using", "sync, SMTP")
Rel_Neighbor(backend_api, banking_system, "Uses", "sync/async, XML/HTTPS")
@enduml
```

**Comment by Mogztter** [comment]
Hey @kjeremy!

> I've embedded the following sample into a markdown file 

Oh, I didn't know that there was a Markdown plugin to render C4 PlantUML diagrams using Kroki! 

> kroki will not render. It complains that `Function not found Container (line: 275)" as in:

It might be related to: https://github.com/plantuml-stdlib/C4-PlantUML/issues/99
I will try to update the C4 PlantUML definition files: https://github.com/yuzutech/kroki/tree/master/server/src/main/resources

For reference, the latest version of Kroki is using PlantUML 1.2020.23.

**Comment by Mogztter** [comment]
I can confirm that updating the C4 PlantUML files fixed this issue.
Please note that the public instance of Kroki won't include remote resources but you can declare icons as follow since tupadr3 is included in the PlantUML standard library:

```
!include <tupadr3/devicons/angular>
!include <tupadr3/devicons/dotnet>
!include <tupadr3/devicons/java>
!include <tupadr3/devicons/msql_server>
!include <tupadr3/font-awesome/server>
!include <tupadr3/font-awesome/envelope>
```

Reference: https://plantuml.com/en/stdlib

**Comment by Mogztter** [comment]
Also I would recommend to use `!include <c4/C4_Container.puml>` instead of `!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml` to include the C4 container definition.

It should be more maintainable and avoid incompatibilities between PlantUML and C4 PlantUML.

**Comment by kjeremy** [comment]
Thank you! I wasn't quite sure about include best practices. 

For reference I am using the gitlab integration with the kroki docker image.

**Comment by kjeremy** [comment]
Can I expect this in the docker image any time soon? Thanks.

**Comment by Mogztter** [comment]
I will probably release a new version later this week.
In the meantime you can [review](https://github.com/yuzutech/kroki/pull/552) and/or checkout the branch [plantuml-service-with-c4](https://github.com/Mogztter/kroki/tree/plantuml-service-with-c4) to build a local version.

**Comment by kjeremy** [comment]
The local version doesn't seem to build for me.

> [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.57 s - in io.kroki.server.ServerTest
> [INFO] Running io.kroki.server.security.SafeModeTest
> [INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.01 s - in io.kroki.server.security.SafeModeTest
> [INFO] Running io.kroki.server.action.CommanderTest
> [ERROR] Tests run: 16, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.367 s <<< FAILURE! - in io.kroki.server.action.CommanderTest
> [ERROR] should_convert_large_diagram  Time elapsed: 0.264 s  <<< ERROR!
> java.io.IOException: Broken pipe
> 	at io.kroki.server.action.CommanderTest.should_convert_large_diagram(CommanderTest.java:95)
> 
> [INFO] 
> [INFO] Results:
> [INFO] 
> [ERROR] Errors: 
> [ERROR]   CommanderTest.should_convert_large_diagram:95 » IO Broken pipe
> [INFO] 
> [ERROR] Tests run: 85, Failures: 0, Errors: 1, Skipped: 0
> [INFO] 
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary for kroki 0.9.0:
> [INFO] 
> [INFO] kroki .............................................. SUCCESS [  0.159 s]
> [INFO] umlet .............................................. SUCCESS [  1.950 s]
> [INFO] kroki-server ....................................... FAILURE [ 16.421 s]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  18.648 s
> [INFO] Finished at: 2021-01-19T10:41:00-05:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project kroki-server: There are test failures.
>

**Comment by Mogztter** [comment]
Maybe you are using an "outdated" version of Node? Could you please run `/usr/bin/node --version`?
Anyway, you can skip tests to build the distribution:

```console
$ mvn package -DskipTests
```

And then:

```console
$ java -jar server/target/kroki-server.jar
```

If you are using [HTTPie](https://httpie.io/):

```console
$ http localhost:8000/plantuml/svg Content-Type:text/plain < diag.puml
```

**Comment by Mogztter** [comment]
@kjeremy I just deployed a new version on https://kroki.io. Please let me know if everything is working as expected now.

**Comment by kjeremy** [comment]
Looks like it's working. Thanks!

**Comment by Mogztter** [comment]
Awesome thanks for your feedback :hugs:
