### ISSUE TITLE
PlantUML proxy uri not work

### ISSUE THREAD

**Issue by ihard** [yuzutech/kroki#577]
In the original PlantUML server, the proxy method works. 
```
curl -iv http://127.0.0.1:8080/plantuml/proxy?src=https://example.domain.com/main_structure.puml
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /plantuml/proxy?src=https://example.domain.com/main_structure.puml HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
```

In Kroki version v0.10.0, I get the HTTP code 404 - was this method cut out for some reason?
```
curl -iv http://127.0.0.1:8000/plantuml/proxy?src=https://example.domain.com/main_structure.puml
*   Trying 127.0.0.1:8000...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> GET /plantuml/proxy?src=https://example.domain.com/main_structure.puml HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 OK
HTTP/1.1 404 OK

```
In logs:
`{"timestamp":"1612194259451","level":"ERROR","thread":"vert.x-eventloop-thread-0","mdc":{"error_message":"OK","path":"/plantuml/proxy","method":"GET","action":"error","error_code":"404","user_agent":"curl/7.68.0"},"logger":"io.kroki.server.error.ErrorHandler","message":"An error occurred","context":"default"}`

**Comment by Mogztter** [comment]
Indeed this service was never part of Kroki.
I purposely want to keep the API as simple as possible. It takes a text diagram as input and returns an image.

In my opinion, a proxy service should not be added in Kroki.
Having said that, someone could work on a proxy to fetch text diagrams from remote URLs and use Kroki as a backend to convert them to images. It could even be an additional services but I don't want to include it in core.

Please keep in mind that you can also use the built-in `include` directive to do pretty much the same:

```
@startuml
!include https://example.domain.com/main_structure.puml
@enduml
```

**Comment by ihard** [comment]
include generally solves my problem - thank you!
