### ISSUE TITLE
Suggest Python Diagrams as Code as new type

### ISSUE THREAD

**Issue by shah** [yuzutech/kroki#582]
Great work putting together the Kroki library! I did not see support for [Diagrams](https://diagrams.mingrammer.com/), which lets you draw cloud system architecture as Python code, and was hoping it could be added to Kroki as an official type. Thanks!

**Comment by Mogztter** [comment]
Thanks @shah!
This is actually a duplicate of https://github.com/yuzutech/kroki/issues/223.
Feel free to add a thumb up or a comment over there :wink:

**Comment by shah** [comment]
Thanks @Mogztter - sorry I missed the original and created a dupe! I've added my thumb up there.
