### ISSUE TITLE
C4 PlantUML missing support for SHOW_DYNAMIC_LEGEND

### ISSUE THREAD

**Issue by koriit-kontakt** [yuzutech/kroki#675]
Hi!
I noticed that C4 PlantUML is missing support for [SHOW_DYNAMIC_LEGEND ](https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md#layout_with_legend-or-show_dynamic_legendhidestereotype) macro function. 

If I understand correctly kroki is replacing stdlib C4 includes with:
https://github.com/yuzutech/kroki/blob/master/server/src/main/resources/c4.puml

And SHOW_DYNAMIC_LEGEND was implemented after the last update to the kroki's file:
https://github.com/plantuml-stdlib/C4-PlantUML/blame/master/C4.puml#L298

Thanks!

**Comment by Mogztter** [comment]
Hi @koriit-kontakt 

Yes that's correct if you are using the public instance kroki.io. If you are using your own instance then you can include any local or remote files.

This feature is not yet available in a release/tag. The latest release/tag is 2.0.1 and does not contain this feature: https://github.com/plantuml-stdlib/C4-PlantUML/blob/v2.0.1/C4.puml

Once this feature is released, feel free to send a pull request to update the files in `server/src/main/resources`.

**Comment by koriit-kontakt** [comment]
Oh, so that's how it is. Thanks for the clarification.

**Comment by koriit-kontakt** [comment]
They just released 2.1.0 :D
https://github.com/plantuml-stdlib/C4-PlantUML/releases/tag/v2.1.0

**Comment by Mogztter** [comment]
resolved in 86d59a090f779153d3cbe8e47494955472596f5b
