### ISSUE TITLE
bitfield support 

### ISSUE THREAD

**Issue by spikie2800** [yuzutech/kroki#697]
Bonjour @Mogztter 

could you please add the support of bitfield https://github.com/wavedrom/bitfield

it would be really great to have it since it's  for the register description

**Comment by Mogztter** [comment]
Bonjour @spikie2800 

I believe that bitfield is now supported on the `/wavedrom` endpoint.


```
{ reg: [
  { "name": "IPO",   "bits": 8, "attr": "RO" },
  {                  "bits": 7 },
  { "name": "BRK",   "bits": 5, "attr": "RW", "type": 4 },
  { "name": "CPK",   "bits": 1 },
  { "name": "Clear", "bits": 3 },
  { "bits": 8 }
]}
```

https://kroki.io/wavedrom/svg/eNqrVihKTbdSiOZSAIJqBaW8xNxUJSsFJc8AfyUdoJBSUmZJMVDAQkdBKbGkpAgkF-SvpFCrA9WBAWA6zBFq4KY6BXmjmGqKbGo4UEqppLIApNIEi2bnAFTNhtjU5KQmFoHMgaoxRlID84lCLVdsLQD1tjqf

**Comment by spikie2800** [comment]
Bonjour @Mogztter 

that's crazy i was trying this morning to get it work without success, most probably I was having a syntax issue 

but now it work fine 

Thank you for your quick feedback

**Comment by Mogztter** [comment]
Cool!
Can we close this issue?


If you want you can create an issue at https://github.com/yuzutech/kroki.io because currently this feature is not documented. We could add an example at https://kroki.io/examples.html

**Comment by Mogztter** [comment]
Closing, feel free to reopen if I missed something.
