### ISSUE TITLE
Automatically update the description on hub.docker.com

### ISSUE THREAD

**Issue by Mogztter** [yuzutech/kroki#698]
The description on hub.docker.com is a bit outdated. We could probably use https://github.com/peter-evans/dockerhub-description to automatically update it from a README.md.

**Comment by lind** [comment]
@Mogztter do you think this #737 could be a way forward for this? 

As mentioned in the PR I think each [dockerhub Kroki repository](https://hub.docker.com/u/yuzutech) should have a separate description file. Or maybe one for [kroki](https://hub.docker.com/r/yuzutech/kroki) and one common for the other images; bpmn, mermaid etc.

I think also the update of the Dockerhub description should trigger whenever there are changes to the description file and not on releases only. It might be good resons to change the description between releases.

**Comment by lind** [comment]
It seems like many of the [official repositories in Dockerhub](https://github.com/docker-library/docs) uses similar structure of the description. Maybe start with a simple structure as [fedora](https://github.com/docker-library/docs/tree/master/fedora)?

**Comment by Mogztter** [comment]
> As mentioned in the PR I think each dockerhub Kroki repository should have a separate description file. Or maybe one for kroki and one common for the other images; bpmn, mermaid etc.

I agree, we should create one description file per companion container.

> I think also the update of the Dockerhub description should trigger whenever there are changes to the description file and not on releases only. It might be good resons to change the description between releases.

True but I also don't want to push changes related to (yet to be released) new features. As suggested in the pull request, we could use `workflow_dispatch` to manually synchronize Docker Hub description when needed.

> It seems like many of the official repositories in Dockerhub uses similar structure of the description. Maybe start with a simple structure as fedora or ubuntu?

Yes we should aim for a simple structure:

- Introduction
- Getting started
	- Prerequisities 
	- Usage
- Versioning
- License

We should also make it clear (in the introduction) that they are *companion* containers and that they are designed to work with `yuzutech/kroki`.
