### ISSUE TITLE
Kroki behaves erratically

### ISSUE THREAD

**Issue by p-vernaeckt** [yuzutech/kroki#710]
Hi.

I just setup Kroki on my server, along with many other services.

Thing is, it behaves erratically. When I create a diagram and pass it in a request, it creates the awaited result one out of 6~7 times, meaning that I need to refresh the page several times to get my diagram.

When the diagram is not generated, I randomly get these errors:

- `Body must not be empty`
- `{"error":"The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}`

Same goes for the Kroki front page, I get these errors and, sometimes, the usual page.

My docker-compose file:
```docker-compose.yml
version: "3"
services:
  kroki:
    image: yuzutech/kroki
    env_file: .env.kroki
    depends_on:
      - blockdiag
      - mermaid
      - bpmn
      - excalidraw
    ports:
      - "8000:8000"

  blockdiag:
    image: yuzutech/kroki-blockdiag
    env_file: .env.kroki
    expose:
      - "8001"

  mermaid:
    image: yuzutech/kroki-mermaid
    env_file: .env.kroki
    expose:
      - "8002"

  bpmn:
    image: yuzutech/kroki-bpmn
    env_file: .env.kroki
    expose:
      - "8003"

  excalidraw:
    image: yuzutech/kroki-excalidraw
    env_file: .env.kroki
    expose:
      - "8004"

networks:
    default:
      external:
        name: mynet
```

The associated env file:
```env
COMPOSE_PROJECT_NAME=kroki

KROKI_BLOCKDIAG_HOST=blockdiag
KROKI_MERMAID_HOST=mermaid
KROKI_BPMN_HOST=bpmn
KROKI_EXCALIDRAW_HOST=excalidraw

UID=1000
GID=1000

LETSENCRYPT_EMAIL=XXXXXXXXXXXXXXXXXX
VIRTUAL_HOST=XXXXXXXXXXXXXXXXXX
LETSENCRYPT_HOST=XXXXXXXXXXXXXXXXXX
VIRTUAL_PORT=8000
```

Can someone help?

PS: I can definitely share the service's URL, but not publicly, for obvious DDOS reasons 😅

**Comment by Mogztter** [comment]
Hello Pierre,

> I just setup Kroki on my server, along with many other services.

You should try to proceed step by step.
The first step would be to run `yuzutech/kroki` (using the default settings) with Docker. Make sure that everything is working fine.
Then, use Docker compose with the "official" compose file: https://docs.kroki.io/kroki/setup/install/#_using_docker_compose. Again, make sure that everything is working fine. 
Then, add the other services.

I can see that you are using let's encrypt in your environment file, are you using a reverse proxy (i.e., TLS termination proxy)? Maybe something is wrong with your configuration?

Could you also provide HTTP requests that do not work?

Thanks

**Comment by jerojasro** [comment]
> When the diagram is not generated, I randomly get these errors:
> 
>     * `Body must not be empty`
> 
>     * `{"error":"The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}`
> 
> 
> Same goes for the Kroki front page, I get these errors and, sometimes, the usual page.

Can you check the logs of your local Kroki instance, for those requests that gave you those errors you mention? I suspect those failed requests are not reaching the Kroki server, and would like to confirm/discard that possibility...

Also, have you tested issuing requests to a Kroki server in localhost? again, to confirm/discard weird networking shenanigans.

**Comment by p-vernaeckt** [comment]
Hi, sorry for the delay.

I tested using directly the IP+port URL, it works every time, so it's not a kroki issue.

Sorry for the inconvenience.

**Comment by Mogztter** [comment]
No worries, I'm glad it's working 👍🏻 

Feel free to share the solution, it can help others with similar infrastructure/environment/technologies.
