### ISSUE TITLE
BPMN: Kroki does't represent a diagram if it contents 2 pools

### ISSUE THREAD

**Issue by taksedo** [yuzutech/kroki#712]
If I create a BPMN diagram. It [works properly](https://kroki.io/bpmn/svg/eNq9XNuO28YZvvdTELrvikOKlLTIbmB7N22A2FnEbm6CQKDIkcSVRGpJ6rB7ZTtAgh5QA0WLBgUKtOgLrNO6dpxk_QrUG3XImSE5JGdEUZJvdlfkzPzff5j_NKP96OPVdCItoOfbrnPSAEdyQ4KO6Vq2Mzxp_PbpJ7_qND4-vfdRfzZ1ji04sB07QCN9CU1z_OPo8UljFASz42ZzuVweudPhkesNm_4Mms0HF48eNxUZyLKmtJqPPj87_6yRmWjZVaeefUrnWSZ_ztlZZsbDZIZdcUZCY-pacAK9ZJppTOeOZeBp5ghOjSYZ0ozlZVsnjbNUND3QXwzVpdmQAsMbwuCxMYX-zDBhsmDE_JHt0sWij0jqq5nrBRHZh5ie9AgTSV99SdXUOmpHhAmKY7iC5jyifTExgoHrTdM16BPB4GTV9hFooWVP70kS1rfpTiZG3_WMaHjM5sPskx4YeKbZNeIZdM7M8ALbtGeGE8QzLtLPPdAdq0YraEgOEslJ44k7hdKTaz-ACN7Mc03o-1_AAZqD_-7Jiyt3IPcbUjPG1CyCSrGS-Zhmfr7tn8dcG_0Joht4c8hgnhgOfAIx3s_w3z25OzBH6oKMy45MhvWA3pG1pZvlx3VgMoVOGkzc5WMkfcTb6X0zsBd2cN2T58HV9VWbMJUdIph9voBIjHIwuHR1d7upvzYCuDQQ3ZtOYAGjHt2-NV6A7aamDA-miylwaxEGbW9o-Pyp5E2kHZG-5EDuulOP6uvCg8ha0QbbjAD0Vd2fmzVZB1O40Lt2XcHpXeBej3fmHow0E94MKPcPXN-vZqoAjgfAm9RlfjBT565ez1rBoD-fda531zx0blyzRXnH3sD1qvI_s6ExrMt_v73o97t17B44w9YMunXtZjwcDX1tC9llHiAXmPWQPgplQQwqlimzKRL3F43J-Ut3HgxdlEqcfoLI9-SrmXoDZ4RM8i5LOyWUJW8ZgfF5_xKaAYIPPZSgYN2eFZ_3ZLV943V1iir8Pvxe-ir8Z3gbvlk_Qz9fhXfrF-G78PbrhsSsm12uB2Yda6FqJPQUceTIc8bPfeg9NfxxPDrvDhKE_4iwhb-Et-vvwtfo99vwtYQA3oW_rJ-vX6yfrb8J3yHIdxH8nHxtlKpNE_kCGQzUG4uIMnkn0og1GtnXQo1QHrJ8BQWeiJNKePrz-g_h-_U36-fhOwkx9Cb8IXy9_h1mb_1SyAVrJVW4YPlmucjkBzPoBdc0QYg_9MBl97qzsCjsXg-nbMgaerMJStlG7sSKMrAmu1hkB586s3lw3_dd007zo7OSF4jISrkcOQVn47tzz4w3pMCO6b5IxuYWSQCf5pkiM9MB7LYv44FRfLBR6cQxJkr_GzLk98huf0JaTgx5S-UzBllJ-d5QH7uLGsqXFytLURaHVb48cGfaUN5a-cO-rA1rKJ8wtW_lczwZjm3Mro_86zOJuLPb8Kf1H2NLQA5XCl-t_4Sc2J3YiTH6rOTEOo7VHSjbOjEOSzjZSVj6F7Ln_yCLvkWu7A4Z8m1Nu2YwVuJKcVeX2tW2XG0XKmMrS3j9C-L2r3WC5Wq6cEewerAsHY-YWdgmLFEJziApzK94OvlarAFGnpU8y0oD2pUuTFdSzBviIy73KA_3Z8glLZBmHOn8iwvxflCupoEz2Ab3HFW6E02EO7-9bSeA3hRayBPAh0ZgjvK5Hqk5GVf_M7L-74jwf4x2_Ov1CzErE8MI3G1YkcdXo5vlQOjcp6jUN4Ywxpm2YWLsj0pfIVMYG5P-MLW_pkAIWTHBlTmZ-_YCkvokJpKrVcQSmF4FQNOEEsjNYIywkvoZgylVf56PyjyS7oGYR8b8KiFm7KJcy7kZbmuyHM7r8pjV9NOR5y4LpQ2uvLjmHvl_5Hzex07yB-SKohiwIa5Bwx7NO9uIhTGWfRk_UG7kzswRGX8qki19RNwfymYD65epdCQUMHNSFAuM0XElb2Ha5pUt71tgS-Um8MztvUVJFMAleVqbFmwoNq28nH4UBzaG60qGxZhipQBRwgvu56VR-d8oU4gSomfh_8L_YpVviMiMc68E3Lx0V-OtgEPHKtgpbicmWvh7VGoj4N-KzZGhzaKlLofQYrOaq3mUbEVrxBiyrDekJLUvBNokdS-TeXMzCeI9Skgkzi1DIh_EKlHAgYahUFinlA2aDFUhgm2VIVLcTxkqOR6rkMDhp5QPGvCKFBJFVaGAXdnWFIg_rUIBB12OmKi8SxSekK9CBOci5USSLH1HqyLurHRrEHmU2hQ1hSokcCnA4YMWgGVUEiarUMElH4cKrZxLqVAIVXSCy2UeL6RBU0qFQqjCC27LcKjQfmY5LwRCFV5wH49jxLTDWEqFQqhCBTtyDhXqYYu7kUaNKuLCLcwy30t75qU2TFlkSARwFdx3HDdIO01PmUfIBrR2sBrmwlc07xQlYc9RLP5ZQjHu1fr36M-olXwbPXgbvpHW36InUeaB6rcoEbmLHqyfozm3-EGU5UYF9tv4Jyrw0MuXUtSXRtX3i6jBK_HrcRqSIyBMjGbgZ3k1ci01ppM2ssagP67ufThSYk6TybFxco5s2cfR1YMz2xh6xjTGkPncA9lzYzL2IjlqSj6hcVI04nwCp0jr4nNzdrUnI2MGeSfnPcvOLVx6vG77v3E9-8Z1UEhgjrtjYpZ5_MCdO5YvrU4aQEWe9vqkoaNfS9sKRuiRBloNaQTt4QgR0LtytgPazEMV85A9Ji-CZw_Rt0GtY9QaACnsVicDW1G7u8Imp8Uc2MlZcg3YWWGzqAHYWdj4lJcnbHoGXAO12uUJGyg72wg5oOUJmx7f1oCttA8Du9y7FBnY4KvzsNsRwkjasp7ZkXKKutXZGvS5NYSF2qOIlKlMsvjsY5TEzVCpFWCX0VZiiG05K7-SgS3QKhnIYI6gbYZMahkOZFrpCJDIqo6lqoohd_XWVuNairYjZ7iG4nFGKqwKQNpaJcCauqsqcD3GA0yqNYEqFLWaiIFMzEzdGTKu73iQSfUnQAIIZK0rFnIycOPOUIk97r4zcGXJ443UnSLIWhfz1t4AWdH1koF1IONSlQeZFLIiwyBuZSNkIHf3BBkXvjzIpCzmI-nQXaptcCtqt2RcDcCkiOb5eFJii7RNwpCmKRvMgsarXWVMinIeZFKy85G0QTUZt0t1UQcwru95gEn1zwei62WS449rgV2tGLcKeFZMGgl8IFrF4KiD1n4cN-k68CRMehICwASIssEkknHdXSWMGxg8CZP2Bh9ISyZAgBhwSy8bVwcw7oXwAJNOiWD7a6BixNP0PUU80lvhGQXpvPCRKJpSScaqXFvGaZHANH2KkNmeEK8kUAAWHegqSUkQ5Q-0IlB1lpEMks-MPpykrworK0QW0c1FsnKU0SYVUotduclbetviSXDhrSgl0S3PTTLraqUiyzuE6iKLlRDZcVpVMjXloSSWb3UWxVRohvJkQ70HaGf6EHKmxOzsUhfnu5kCoLTfyQNKt-CBgZIWtUiipIm9SaJxADkgUNyxFwElPX0eUB18GKD4AEMoUXzEsQlonPTsHajgMlxV94NvznEtt0P6DfK-_Y9K6jVVT4NBV_6gDgi32kXKJc14bo9LP6Ry88eeIgdEDkZ5QLsg0zXZO1DmHJmXHNBjZn4Dn7QS9M6-swOgAg0vrXWSpdudD2BruXPjomwKB8u2_8jwxtD70vbt_Jf8SvRK62wl3Z7ZHqu2i1pzJ-t88MnR-3bg07ZG6wDomesT3IyV3K7gQkz6rWDvRikrKunrp9zrIHOG0j6QUTKXEPjbFd9R4EomaaNpB9iuClm6ndqF9gEkk7-EIfK45JoGXz7qB8lQyDm_CCm5CcBFSk83dP2AwQFfOuBaG7mTwMVIq-4DBAdN7-BCKONDVeVgwSFpApRcCSjRYsm9AUF7Njp2LXTYSsbJbezVtFbtHoboG2LluWeV75NxehzsCWdJj0NrbTduhyav6NtRFRkv-S5VvjGmKJValC19ixYl8_iCfl2WeUruh5zeo9-vSv8dxOm9_wPgeayz)

But if I add 2nd pool, the diagram [breaks down](https://kroki.io/bpmn/svg/eNq9XNuO28YZvvdTELrvikOKlLTwbmB7N20A21nEbm6CQKDIkcSVREokddi9sh0gQQ-ogaJFgwIFWvQF1mldO06yfgXpjTrkzJAckjOiKGlvvLvUzPzff5j_SPn-J8vxSJpDz7dd56QGjuSaBB3TtWynf1L77fNPf9WqfXJ67353MnaOLdizHTtAK30JbXP84_DxSW0QBJPjen2xWBy54_6R6_Xr_gSa9YcXT57WFRnIsqY06k8-Pzt_XEtttOyyW88-o_ssk7_n7Cy141G8wy65I6Yxdi04gl68zTTGM8cy8DZzAMdGnSypR_KyrZPaWSKaDujO--rCrEmB4fVh8NQYQ39imDA-MGT-yHbpYeGfSOrLiesFIdlHmJ70BBNJPvqSqqlx1AwJExTHcAnNWUj7YmQEPdcbJ2fQJ4LF8anNI9BAx57ekySsb9MdjYyu6xnh8ojNR-knHdDzTLNtRDvononhBbZpTwwniHZcJH93QHuoGo2gJjlIJCe1Z-4YSs-u_AAieBPPNaHvfwF7aA_-vSPPp25P7takemkKVm_cmg84x40vp3PFIsfdr-d5TFgn-zGBLBzbP4-EaHRHiI3Am0FGBCPDgc8gBvcY_96R2z1zoM7JuvTKeFkH6C1ZW7hp8bgOjLfQTb2Ru3iKlIl4O31gBvbcDq468iyYXk2bhKn0EsHu8zlEMpOD3qWru9tt_bURwIWB6F63AgsY1eh2reEcbLc1Ybg3no-BW4kwaHp9w-dvJZ-E2hHpSw7ktjv2qL4uPIhME93XzQhAV9X9mVmRdTCGc71tVxWc3gbu1XBn7sFAM-F1j3L_0PX9cqYK4LAHvFFV5nsTdebq1awV9LqzSetqd81D59o1G5R37A1cryz_Exsa_ar8d5vzbrddxe6B029MoFvVbob9Qd_XtpBd6gFygWkP6aPIGESgIpkylyJ2f-GajL90Z0HfRZnJ6aeIfEeeTtRrOCFk4s_StBNCafKWERifdy-hGSD40EP5DtbtWf55R1ab115bp6hW36--l75a_XN1s3q3foH-fbO6Xb9afVjdfF2TmHPTx3XApGXNVS0TyZL1GfKc9TMfes8NfxitzrqDGOE_QmyrX1Y36-9Wb9HP96u3EgJ4u_pl_XL9av1i_c3qA4J8G8LPyNdGmd84li-QQU-9togo489EGrEGA_tKqBHKQ5qvIMcTcVIxT39e_2H1cf3N-uXqg4QYerf6YfV2_TvM3vq1kAvWSspwwfLNcpHKDybQC65oghD90QGX7avW3KKwOx2cASJr6ExGKAMcuCMrTOjq7GGhHXzmTGbBA993TTtJt84KPkBElsrlwMk5G9-deWZ0IQV2TO9FvDZzSAz4NMsU2ZksYK99EQ-M4oONSieOMVb635Ahf0R2-xPScmzIWyqfMchSyvf6-tCdV1C-PF9aijI_rPLlnjvR-vLWyu93Za1fQfmEqX0rn-PJcGxjbn3oX19IxJ3drH5a_zGyBORwpdWb9Z-QE7sVOzFGn6WcWMux2j1lWyfGYQknOzFL_0L2_B9k0TfIld0iQ76paNcMxlJcKe7yUptuy9V2oTKyspjXvyBu_1olWC7Hc3cAywfLwvWImbltwgKV4AySwvyKp5OvxRpg5FnKsyw1oE11YbqSYN4QH3G5R3l4MEEuaY4040jnX1yI74MyHQdObxvcM1TpjjQR7uz1tp0AemNoIU8AHxmBOcjmeqTmZFz9z8j6vyPC_zG88W_Xr8SsjAwjcLdhRR5OB9eLntC5j1Gpb_RhhDPp6kTYnxR-hExhaIy6_cT-6gIhpMUEl-Zo5ttzSOqTiEimVhFLYDwNgKYJJZDZwRhhKfUzBlOo_iwfpXkk3QMxj4z5lULM2EWxljM73MZo0Z9V5TGt6ecDz13kShtceXHNPfT_yPl8jJzkD8gVhTFgQ1yDhj2YtbYRC2Ms-zJ-oFzLrYkjMv5EJFv6iKg_lM4G1q8T6UgoYGakKBYYo-NS3sK0zakt71tgC-U68MztvUVBFMAleVKb5mwoMq2snH4UBzaG61KGxZhiqQBRwAvu5yVR-d8oUwgToher_63-i1W-ISIzzr0UcPPSXQ63Ag4dK2enuJ0Ya-HvYamNgH8rNkeGNouWuhxCi81qprMw2QrPiDCkWa9JcWqfC7Rx6l4k8_pmEsR7FJCInVuKRDaIlaKAAw1DIXdOIRs0GSpDBNsqQyR_n1JUMjyWIYHDTyEfNODlKcSKKkMBu7KtKRB_WoYCDrocMVF5Fyg8Jl-GCM5FionEWfqOVkXcWeHVIPIotClqCmVI4FKAwwctAIuoxEyWoYJLPg4VWjkXUqEQyugEl8s8XkiDppAKhVCGF9yW4VCh_cxiXgiEMrzgPh7HiGmHsZAKhVCGCnbkHCrUw-ZvI40aZcSFW5hFvpf2zAttmLLIkAjgMnjgOG6QdJqeM4-QDWjNYNnPhK9w3ylKwl6iWPyzhGLcm_Xv0a9hK_kmfPB-9U5af4uehJkHqt_CROQ2fLB-ifbc4AdhlhsW2O-jf1GBhz58LYV9aVR9vwobvBK_HqchOQTCxGgGfppXI9NSYzppA2sIusPy3ocjJWaaTMbGG-bIdA7NzpF7xsinTYz7-P2I4_A1iDPb6HvGODoi9XcHpIfOZO1FPKeK_0LrpHDF-QiOkcmIZ_jsac8GxgTypvgdy84cXDjqt_3fuJ597ToonjCz8oiYZR4_dGeO5UvLkxpQkZu-Oqnp6MfCtoIBeqSBRk0aQLs_QAT0tpxun9azUMU8pCd3efDsXG8b1DpGrTRBArvRSsEGys6wybCVAzsexVaArbYPCJtMyHnSpvPzCrDTNsKgVgDYWdj4PQyesOlbGhVQa4AnbEVtbw373OrDXJDIo2ZCSBqhfYySqQkqeYIQo6Ip2I5BWu35darcKFjHIA6BbQZMAicHMA2rfCDYNyAkTVmMGGi6XrCwCmScUfAgk3yDj6RRKLuCdfqeZEwSLZ5RkDSMD4SKWNHEgON17V0ljPNPnoRJdioAQiSnqmLAOihaV0XCOC3nSZgk7QIgFHBzA2CyrrGzSeBqhQeY1DJ8IE0iucYGk2jqReuqAMYVHA8wqe8E119pYSRa6OHqJRayuqhixbiy5VkxqXv5SFp6ORm3w6ixDxmTep8HmHQDBKKTiVVoG8wYALldsLAKZNwE4UEmLRIREq1dDrJCwsfukHFniAeZ9I1EkFUi5ba2QcpqydCoqvsKjbixxuONtN1EUlbLeW4gN5X9uG7ScORBJu1Iwe2jt7Qp1gZdp-0MGPdgeYBJh1YkOqLtTTJul4yisQQUbUcfjxvYPB9P2tsiOyZGsdHgG4VJYynISZnANF_yoNneDK8oUABWBmgrcVEQ6oeWBKrOcpJC8tjowlHyUe5khaTy4RuE5ORQQ3Fl12BPrvOO3rZ8Erx4lpeS6G3LTTJra4Uiy4bL8iKLlBCaRVKgMbXwoSSWbTnmxZRrSvJkQ4sG0EzVxqGVUyZau9Tz2a6iACjtO_KA0grywEBJq1gkUdJM3iTRqKo5IFDcORcBJb11HlAd3A1QPEgQShSPGjYBjaqYvQMVvJRW1v3gN9i4ltsi8VPet_9RSTKq6kkwaMt36oBwy1ukXNIU50mnqR9Sudnxo8gBkQElD2gbpBKyvQNl5rm85ICOe_m9cJKq6a19ZwdABRo-WmvFRzdbd2BrmfltXja5Aa_tPzG8IfS-tH07-2W7Ar3SclhJrqcmc65nVfBkws0HH4_AtwOfVMaNA6BnXmPgZqzkLQcuxLh-AHs3SllRyRgl4V4HqQZ580BGybwMwL-u-F0BrmTiHoF2gOuqkKObiV1odyCZ7MsQIo9LXpfgy0e9kwyFzNtFSMlEnouUFoi6fsDggIf_XGsj7wZwMdKBxgGCg6a3cCGU8qGqcgfBoXi8nhfRhpcVckkJ7enKemqqnFJno1V98FbwPkGB6RW8dCBo_YYjwlyfv2Cd3MR8aY3qfYyCr85vGOvT79dXGOu3UtmWnr5QSoXIFqtA9BW54qS_zBfqOLNRdiReMBvVGtut26GjLPp6WEnGC75Mlh1EKkqpRmBD32Kcxjy-oN8XZp6Sd1xO79EvmCX_vcbp_wEtbRhi)

**Comment by Mogztter** [comment]
Hello,

It's related to https://github.com/yuzutech/kroki/issues/555
The second diagram returns a 414 Error:

![image](https://user-images.githubusercontent.com/333276/116260714-38c03700-a777-11eb-9e77-8eeec7fec76d.png)

If you are using your own instance, you can increase the default max URI length: https://docs.kroki.io/kroki/setup/configuration/#_max_uri_length

Otherwise, you will need to send your diagram using a POST request: https://docs.kroki.io/kroki/setup/usage/

**Comment by taksedo** [comment]
Can it be fixed if I use kroki.io?

**Comment by Mogztter** [comment]
@taksedo as mentioned above, you will need to send your diagram using a [POST request](https://docs.kroki.io/kroki/setup/usage).
We might increase this value a bit in the future but the fact remains that web servers have a maximum URI length. I guess this limit is set to prevent abuse (memory over allocation, potential security threats...).
Browsers also have URI limits: https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers/417184#417184

**Comment by taksedo** [comment]
It works with self-hosted kroki instance, thank you!
