### ISSUE TITLE
PlantUML C4 support from behind firewall

### ISSUE THREAD

**Issue by lind** [yuzutech/kroki#718]
I get an error using C4 in PlantUML from behind a firewall. It's a 400 `Cannot open URL (line: 504)` but in the log it's also a:
`issue raw.githubusercontent.com java.util.concurrent.ExecutionException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target` 
This log is probably from PlantUML itself...?

If I downgrade Kroki to 0.11.0 I don't get the exception so I wonder if it is related to the [include](https://github.com/yuzutech/kroki/blob/main/server/src/main/resources/c4_component.puml#L5) in the C4 files introduced in https://github.com/yuzutech/kroki/issues/675

Is the `include` needed? It's not present in [the 0.11 version](https://github.com/yuzutech/kroki/tree/v0.11.0/server/src/main/resources)

I tried to set env.var: `RELATIVE_INCLUDE` to . but with the same error.

It might be related to this issue: https://github.com/yuzutech/kroki/issues/578

**Comment by Mogztter** [comment]
@lind Could you please share a simple diagram definition that reproduces this error? Depending on how you include C4, Kroki will either to delegate to PlantUML or use local files.

> Cannot open URL (line: 504) but in the log it's also a: issue raw.githubusercontent.com java.util.concurrent.ExecutionException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

In any case, I wasn't expecting PlantUML to do a remote call...

**Comment by lind** [comment]
Yes @Mogztter the "standard" C4 diagram [Internet Banking System](https://kroki.io/c4plantuml/svg/eNp9UkFuwjAQvOcVW05Uopz6AErEgQMVKvQcGbNJLBwbeTeC_r4b40AQtLd4PDszO86MWAVuG5u9GKdtu0fI34vcO8YzT4_dRcaGLcLmhxgbSFewN6oKqoHSB1gKFBwyzJU7GFclbpatMZB3Y90S-wbDBEY9I0_QSLAP6AngS-AaYSesCZwM13CMEspGDJTWvnVM09FrdjEZ7y6KBcWjyP2RJjpZ6090tSNgD7pGfehcTbiTT_rF4szjRhl7M1i8dWegq-xWIpvoKjlXRgdPvmRYnHWtXIWAw4Fb9F7alVIkis6q_34SfcM-IIGyti9JCwBpe7GXh2gUG-9i-C-0g9ofOvomJKEJq5grfRhQ71fdoNtTyt-1lWY-0VT1zoeH8v-ZjkustuuLxLPJaw8p3UzG5Qf8BSot7V4=) from kroki.io 
works fine on your OpenShift cluster on Kroki v. 0.11.0 but not on 0.12.0/0.12.1
In the log: `issue raw.githubusercontent.com java.util.concurrent.TimeoutException`

Is it possible to remove the external include in the [c4_component.puml](https://github.com/yuzutech/kroki/blob/main/server/src/main/resources/c4_component.puml#L5) and the other puml files?

**Comment by lind** [comment]
@Mogztter I assume the [include in the _puml_](https://github.com/yuzutech/kroki/blob/d56b2fe425448c03adc2fbd2b1e7916e9eb528c7/server/src/main/resources/c4_container.puml#L2) files is not needed at all since the inclusion is already handled in [Plantuml.java](https://github.com/yuzutech/kroki/blob/main/server/src/main/java/io/kroki/server/service/Plantuml.java#L95). Is that correct?

**Comment by Mogztter** [comment]
>  I assume the include in the puml files is not needed at all since the inclusion is already handled in Plantuml.java. Is that correct?

@lind Yes that's correct! I totally missed that when I reviewed: https://github.com/yuzutech/kroki/pull/681.
We can indeed remove the following blocks:

https://github.com/yuzutech/kroki/blob/d56b2fe425448c03adc2fbd2b1e7916e9eb528c7/server/src/main/resources/c4_component.puml#L1-L6

https://github.com/yuzutech/kroki/blob/d56b2fe425448c03adc2fbd2b1e7916e9eb528c7/server/src/main/resources/c4_container.puml#L1-L6

https://github.com/yuzutech/kroki/blob/d56b2fe425448c03adc2fbd2b1e7916e9eb528c7/server/src/main/resources/c4_context.puml#L1-L6

https://github.com/yuzutech/kroki/blob/d56b2fe425448c03adc2fbd2b1e7916e9eb528c7/server/src/main/resources/c4_deployment.puml#L1-L6

https://github.com/yuzutech/kroki/blob/d56b2fe425448c03adc2fbd2b1e7916e9eb528c7/server/src/main/resources/c4_dynamic.puml#L1-L6
