### ISSUE TITLE
AddRelTag is not working

### ISSUE THREAD

**Issue by kysee** [yuzutech/kroki#747]
I set the line color and text color by using AddRelTag.
As you see in the following diagram,
the color is not changed and the tags are not shown in the legend table.

Please refer to [this issue](https://github.com/marcozaccari/markdown-diagrams-browser-extension/issues/3) for details.

**Comment by Mogztter** [comment]
For reference, this feature was introduced in version 2.2.0: https://github.com/plantuml-stdlib/C4-PlantUML/releases/tag/v2.2.0
