### ISSUE TITLE
K8s deployment - wrong port for excalidraw service

### ISSUE THREAD

**Issue by lind** [yuzutech/kroki#807]
There are one minor error in the excalidraw service. The port should be `8004` I presume since the [excalidraw-deployment container port](https://github.com/yuzutech/kroki/blob/main/docs/modules/setup/examples/k8s/excalidraw-deployment.yaml#L22) is `8004`.

https://github.com/yuzutech/kroki/blob/b6e6ae824af79937c01023ac218703619f23ab47/docs/modules/setup/examples/k8s/excalidraw-service.yaml#L11

**Comment by lind** [comment]
PR: https://github.com/yuzutech/kroki/pull/808

**Comment by Mogztter** [comment]
Fixed in https://github.com/yuzutech/kroki/commit/8a2a91d5ee2aeae53ceb171556f1f854fb2f90ff and thanks again 😉
