### ISSUE TITLE
Kroki integration in GitLab not rendering in Chrome

### ISSUE THREAD

**Issue by vioan** [yuzutech/kroki#809]
I have Kroki setup as a self hosted service and integrated with GitLab. 

I added some diagrams in a few markdown files and they are rendered in Firefox/Safari but it seems that Chrome/Edge is just showing a placeholder (small icon) for the images/diagrams. The image/diagram is available via Kroki instance, as I can right click on placeholder and is opened in browser on Kroki server.

Any idea what can be? Is that a GitLab UI/rendering issue or is something related to Kroki?

Thank you very much.

**Comment by vioan** [comment]
ok, I found the issue. Chrome by default doesn’t allow/embed “http” images in sites with “https”.

temp fix:
- change the settings in chrome: chrome://settings/content/siteDetails?site=https://gitlab-url/ , and change “Insecure content” to "allow".

permanent fix:
- add an Nginx with TLS in front of Kroki service.

**Comment by Mogztter** [comment]
Thanks for the follow-up.
Might be worth to explain how to do it in the documentation but let's continue the discussion here: https://github.com/yuzutech/kroki/issues/787
