### ISSUE TITLE
Choose port 8000 or 8080 to expose in the examples and make the test conform in the docs.

### ISSUE THREAD

**Issue by sturtison** [yuzutech/kroki#810]
The install page doco currently configures port **8**000 in the docker-compose.yml but then asks the reader to test using port **8**0**8**0 afterwards.

https://github.com/yuzutech/kroki/blob/2d9c868c48f261242c625357e85b0dc882c75ab2/docs/modules/setup/examples/kroki-docker-compose.yml#L15-L16

https://github.com/yuzutech/kroki/blob/2d9c868c48f261242c625357e85b0dc882c75ab2/docs/modules/setup/pages/install.adoc#L151-L153

**Two options:** The docs could either: 
* **Be consistent with the preceding gateway server example** and change the port in the example docker-compose.yml file to 8080.  This would change the behavior of the example, perhaps confusing existing installs who may expect port 8000. Positively for the growing number of installations, it reads more consistently.
* **Be consistent with the example docker-compose file** and change the port tested afterwards. This changes the doco only but leaves the reader wondering why the change to 8000.

**Proposal:** For long term readability and use I suggest the first option over the second however I don't know any of the reasons for going with port 8000 to begin with.

A change could be made either way while splitting out the installs for the containers, kubernetes and manual.

**Comment by Mogztter** [comment]
I think we should stick with the default port 8000. The example using port 8080 is here to demonstrate how to map to a different port.

Maybe we should use a `NOTE:` to explain that it's possible to map to another port but use the same port on all examples:


```
By default, when you start a container, it does not publish any of its ports to the outside world.
To make a port available to services outside of Docker or Podman, you need to use the `--publish` or `-p` flag.

Using docker::

[source,docker-cli]
docker run -p8000:8000 yuzutech/kroki

Using podman::

[source,podman-cli]
podman run -p8000:8000 yuzutech/kroki

[NOTE]
====
You can also map a different TCP port on the Docker host.
For instance, if you want to map your host's TCP port 1234 to port 8000 in the Kroki container, use: `-p1234:8000`.
====
```

Does it make more sense?

**Comment by Mogztter** [comment]
Fixed in https://github.com/yuzutech/kroki/commit/6d49fceaf10e3f746bc07c29a045b5da497cde01.
