### ISSUE TITLE
Running kroki on 32bit system

### ISSUE THREAD

**Issue by muratakburak** [yuzutech/kroki#9]
Hello Mr. @Mogztter  I wanted to run kroki on my 32bit ubuntu server to get my hands on the docker but I get the error in the screenshot when I try to build docker images. Is it not possible to do it on a 32bit system or am I missing something here? Sorry for posting here I am not able to use mailing services atm.
![Screenshot (2)](https://user-images.githubusercontent.com/8910577/57432743-5c62dd80-723f-11e9-8367-95d7e42a03b5.png)

**Comment by Mogztter** [comment]
Hello @muratakburak 

To be honest, I don't know if it's possible to build a 64 bits binary on a 32 bits host system.
But if you just want to use Kroki, you don't need to build the Docker images.

You can just type:

```console
$ docker run -d -p 8000:8000 yuzutech/kroki
```

I've just noticed that the Nomnoml is not yet published on Docker hub, I will take care of it in a few days.

https://cloud.docker.com/u/yuzutech/repository/docker/yuzutech/kroki-mermaid
https://cloud.docker.com/u/yuzutech/repository/docker/yuzutech/kroki-blockdiag
https://cloud.docker.com/u/yuzutech/repository/docker/yuzutech/kroki

**Comment by muratakburak** [comment]
I just pulled kroki from Docker hub and ran the command: 
`$ docker run -d -p 8000:8000 yuzutech/kroki` 
There is no running container afterwards and I can see it as `Exited(1)` when I type `$ docker ps -a`

**Comment by Mogztter** [comment]
Could you please try without the `-d` option (daemon) or use `docker logs` to get the error ?

**Comment by muratakburak** [comment]
Sure, thanks for the quick responses! It gives the error:
`standart_init_linux.go:207: exec user process caused "exec format error"`

**Comment by Mogztter** [comment]
I'm not a Docker expert but it looks like the image is not compatible with a 32 bits system. I will update the documentation accordingly, sorry 😥 

Could you please try one last thing ?
Type the following command in the `server` directory:

```console
$ sudo make package
```

The above command will only build the gateway server. Since you are using a 32 bits system, it should build an image that's compatible with your architecture.
And then you can run server using:

```console
$ sudo make run
```

The above command is equivalent to:

````console
$ sudo docker run yuzutech/kroki:latest
````

**Comment by muratakburak** [comment]
It outputs:
![Screenshot (3)](https://user-images.githubusercontent.com/8910577/57597944-0309ef80-755a-11e9-9773-b5d8782a98f1.png)

**Comment by Mogztter** [comment]
Sorry I forgot that the server is using Nomnoml so if you can't build the Nomnoml image on a 32 bits then you won't be able to build the server image.

**Comment by muratakburak** [comment]
Alright, thanks for your help.
