### ISSUE TITLE
Upgrade C4 PlantUML to version 2.3.0 (4 july 2021)

### ISSUE THREAD

**Issue by Gowa2017** [yuzutech/kroki#920]
Respect to upgrade it.

**Comment by Mogztter** [comment]
I can find the version 2.4. The latest tag on GitHub is 2.3.0: https://github.com/plantuml-stdlib/C4-PlantUML/releases/tag/v2.3.0

**Comment by Gowa2017** [comment]
Sorry, v2.4 othe master branch

**Comment by Mogztter** [comment]
@Gowa2017 No worries, we are currently using version 2.2.0, so we can upgrade to version 2.3.0.

**Comment by Gowa2017** [comment]
I try de use the version 2.4.0, all is ok.
This server deployed on my server:

![test](http://42.192.43.15:9999/plantuml/svg/SoWkIImgAStDKIX9BIxXKipCIyufJKbLS3Q9TyxFBSZFIyqhqIi0odCvcuIb5XLdvkUvf9OaPkOKQsXoEQJcfG2b0000 "test")

**Comment by Mogztter** [comment]
That's a good news but we only use "stable" version (i.e., tagged) in Kroki. The latest version available is 2.3.0.

Version 2.4.0beta1 is still in development (master branch) and not yet "stable".

**Comment by paalpri** [comment]
Hi! 

Seems[ version 2.4.0](https://github.com/plantuml-stdlib/C4-PlantUML/releases) is available and the latest release now. Any plans to update the c4 stdlib to version 2.4.0 ? Would love to have the custom legendText feature available in 2.4.0.

**Comment by Mogztter** [comment]
Please open a new issue and if you want to submit a pull request I will be more than happy to merge it.
